/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasAdministrativo;

import Controlador.FuncionDAO;
import Controlador.PeliculaDAO;
import Modelo.Funcion;
import Modelo.Pelicula;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Enzo_2
 */
public class DialogCambiarFuncion extends javax.swing.JDialog {

    /**
     * Creates new form DialogCambiarFuncioon
     */
    private int idFuncion = -1;
    
    FuncionDAO maniFuncion = new FuncionDAO();
    PeliculaDAO maniPeli = new PeliculaDAO();
    
    List<Pelicula> listaCartelera = maniPeli.listarPeliculasEnCartelera();
    List<Funcion> listaFuncionPorPelicula;
    
    String[] cabeceraCartelera = {"ID","Titulo", "Director", "Reparto", "Pais de origen", "Genero/s"};
    String[] cabeceraFunciones = {"ID","Número de sala", "Idioma", "3D", "Hora de inicio", "Hora finalización", "Precio de entrada",
        "Fecha de función", "Subtitulada"};
    
    int id_peliculaS = -1;
    int nro_sala = -1;
    boolean estadoExito;
    
    public DialogCambiarFuncion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tblCartelera.setModel(VentanaAdministrativo.armarCabeceras(cabeceraCartelera));
        tblFunciones.setModel(VentanaAdministrativo.armarCabeceras(cabeceraFunciones));
        rellenarTablaPelicula();
        agregarListenerCartelera();
        agregarListenerFunciones();
        btnConfirmar.setEnabled(false);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCambiarFuncion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFunciones = new javax.swing.JTable();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCartelera = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblCinemaCentro = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        lblFuncion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlCambiarFuncion.setBackground(new java.awt.Color(102, 0, 0));

        tblFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblFunciones);

        btnConfirmar.setBackground(new java.awt.Color(70, 73, 75));
        btnConfirmar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar cambio");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(70, 73, 75));
        btnCancelar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar cambio");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblCartelera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblCartelera);

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("CAMBIAR FUNCION");

        lblCinemaCentro.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblCinemaCentro.setForeground(new java.awt.Color(255, 255, 255));
        lblCinemaCentro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCinemaCentro.setText("CinemaCentro");

        lblPelicula.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblPelicula.setText("Pelicula:");

        lblFuncion.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblFuncion.setForeground(new java.awt.Color(255, 255, 255));
        lblFuncion.setText("Funcion:");

        javax.swing.GroupLayout pnlCambiarFuncionLayout = new javax.swing.GroupLayout(pnlCambiarFuncion);
        pnlCambiarFuncion.setLayout(pnlCambiarFuncionLayout);
        pnlCambiarFuncionLayout.setHorizontalGroup(
            pnlCambiarFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiarFuncionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCambiarFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCambiarFuncionLayout.createSequentialGroup()
                        .addGroup(pnlCambiarFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCambiarFuncionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(291, 291, 291))
                    .addGroup(pnlCambiarFuncionLayout.createSequentialGroup()
                        .addComponent(lblFuncion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCambiarFuncionLayout.createSequentialGroup()
                        .addGroup(pnlCambiarFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCambiarFuncionLayout.createSequentialGroup()
                                .addComponent(lblPelicula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlCambiarFuncionLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTitulo)
                                .addGap(57, 57, 57)))
                        .addComponent(lblCinemaCentro)
                        .addContainerGap())))
        );
        pnlCambiarFuncionLayout.setVerticalGroup(
            pnlCambiarFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiarFuncionLayout.createSequentialGroup()
                .addGroup(pnlCambiarFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCambiarFuncionLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(pnlCambiarFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitulo)
                            .addComponent(lblCinemaCentro))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCambiarFuncionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPelicula)
                        .addGap(8, 8, 8)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFuncion)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlCambiarFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCambiarFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCambiarFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        estadoExito = false;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        estadoExito = true;
        this.dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    public boolean isEstadoExito() {
        return estadoExito;
    }

    public int getIdFuncion() {
        return idFuncion;
    }
    
    public void ocultarIDs() {

        TableColumnModel modeloColumnasP = tblCartelera.getColumnModel();
        TableColumnModel modeloColumnasF = tblFunciones.getColumnModel();
        TableColumn columnaP = modeloColumnasP.getColumn(0);
        TableColumn columnaF = modeloColumnasF.getColumn(0);
        columnaP.setMaxWidth(0);
        columnaP.setMinWidth(0);
        columnaP.setPreferredWidth(0);
        columnaP.setResizable(false);

        columnaF.setMaxWidth(0);
        columnaF.setMinWidth(0);
        columnaF.setPreferredWidth(0);
        columnaF.setResizable(false);
    }
    
    public void rellenarTablaPelicula() {
        DefaultTableModel modelo = (DefaultTableModel) tblCartelera.getModel();
        modelo.setRowCount(0);
        for (Pelicula p : listaCartelera) {
            modelo.addRow(new Object[]{p.getId_Pelicula(),
                p.getTitulo(),
                p.getDirector(),
                p.getReparto(),
                p.getPais_Origen(),
                p.getGenero()
            });
        }
    }
    public void rellenarTablaFunciones(int id_pelicula) {
        DefaultTableModel modelo = (DefaultTableModel) tblFunciones.getModel();
        modelo.setRowCount(0);
        try {
            listaFuncionPorPelicula = maniFuncion.listadoPorId(id_pelicula);

            for (Funcion f : listaFuncionPorPelicula) {
                modelo.addRow(new Object[]{f.getId_Funcion(),
                    f.getNro_Sala(),
                    f.getIdioma(),
                    parsearBoolean(f.isEs3D()),
                    f.getHora_Inicio(),
                    f.getHora_Fin(),
                    f.getPrecio_Entrada(),
                    f.getFecha_Funcion(),
                    parsearBoolean(f.isSubtitulada())
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    public void agregarListenerCartelera() {
        tblCartelera.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent evento) {
                if (evento.getValueIsAdjusting()) {
                    return;
                }
                int filaS = tblCartelera.getSelectedRow();
                if (filaS != -1) {
                    id_peliculaS = (int) tblCartelera.getValueAt(filaS, 0);
                    rellenarTablaFunciones(id_peliculaS);
                }
            }
        });
    }

    public void agregarListenerFunciones() {
        tblFunciones.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent evento) {
                if (evento.getValueIsAdjusting()) {
                    return;
                }
                
                int filaS = tblFunciones.getSelectedRow();
                
                if (filaS != -1) {
                    nro_sala = (int) tblFunciones.getValueAt(filaS, 1);
                    idFuncion = (int) tblFunciones.getValueAt(filaS, 0);
                    btnConfirmar.setEnabled(true);
                } else {
                    btnConfirmar.setEnabled(false);
                }
            }
        });
    }
    public String parsearBoolean(boolean estado) {
        if (estado) {
            return "Si";
        }
        return "No";
    }

    public boolean parsearString(String estado) {
        return estado.equalsIgnoreCase("Si");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCambiarFuncion dialog = new DialogCambiarFuncion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCinemaCentro;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlCambiarFuncion;
    private javax.swing.JTable tblCartelera;
    private javax.swing.JTable tblFunciones;
    // End of variables declaration//GEN-END:variables
}
