/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasAdministrativo;

import Controlador.AsientoDAO;
import Modelo.Asiento;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enzo_2
 */
public class DialogAsientos extends javax.swing.JDialog {

    /**
     * Creates new form DialogAsientos
     */
     
    AsientoDAO maniAsi = new AsientoDAO();
    List<Asiento> listaAsientos = maniAsi.listarAsientosPorSala(1);
    
    public DialogAsientos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rellenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAsientos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsientos = new javax.swing.JTable();
        pnlPantalla = new javax.swing.JPanel();
        lblPantalla = new javax.swing.JLabel();
        lblSala = new javax.swing.JLabel();
        lblNroSala = new javax.swing.JLabel();
        lblNombrePelicula = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        lblHorarioPelicula = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblAsientos = new javax.swing.JLabel();
        lblAsientosLibres = new javax.swing.JLabel();
        lblCinema = new javax.swing.JLabel();
        pnlEntrada = new javax.swing.JPanel();
        lblEntrada = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlAsientos.setBackground(new java.awt.Color(102, 0, 0));
        pnlAsientos.setForeground(new java.awt.Color(102, 0, 0));
        pnlAsientos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAsientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "A", "B", "C", "D", "E", "F", "G", "H", "I", "J"
            }
        ));
        tblAsientos.setCellSelectionEnabled(true);
        tblAsientos.setRowHeight(23);
        jScrollPane1.setViewportView(tblAsientos);

        pnlAsientos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 892, 570));

        pnlPantalla.setBackground(new java.awt.Color(102, 0, 0));
        pnlPantalla.setForeground(new java.awt.Color(255, 255, 255));

        lblPantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pantalla.png"))); // NOI18N
        lblPantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlPantallaLayout = new javax.swing.GroupLayout(pnlPantalla);
        pnlPantalla.setLayout(pnlPantallaLayout);
        pnlPantallaLayout.setHorizontalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPantallaLayout.setVerticalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPantallaLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(lblPantalla)
                .addGap(105, 105, 105))
        );

        pnlAsientos.add(pnlPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 235, -1, 560));

        lblSala.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblSala.setForeground(new java.awt.Color(255, 255, 255));
        lblSala.setText("SALA N°:");
        pnlAsientos.add(lblSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lblNroSala.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblNroSala.setForeground(new java.awt.Color(255, 255, 255));
        lblNroSala.setText("NUMEROSALA");
        pnlAsientos.add(lblNroSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        lblNombrePelicula.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblNombrePelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePelicula.setText("NOMBRE PELICULA");
        pnlAsientos.add(lblNombrePelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        lblPelicula.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblPelicula.setText("PELICULA:");
        pnlAsientos.add(lblPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblHorarioPelicula.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblHorarioPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblHorarioPelicula.setText("HORARIOPELICULA");
        pnlAsientos.add(lblHorarioPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        lblHorario.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblHorario.setForeground(new java.awt.Color(255, 255, 255));
        lblHorario.setText("HORARIO:");
        pnlAsientos.add(lblHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblAsientos.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblAsientos.setForeground(new java.awt.Color(255, 255, 255));
        lblAsientos.setText("ASIENTOS:");
        pnlAsientos.add(lblAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        lblAsientosLibres.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblAsientosLibres.setForeground(new java.awt.Color(255, 255, 255));
        lblAsientosLibres.setText("ASIENTOSLIBRES");
        pnlAsientos.add(lblAsientosLibres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        lblCinema.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblCinema.setForeground(new java.awt.Color(255, 255, 255));
        lblCinema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCinema.setText("CINEMACENTRO");
        lblCinema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlAsientos.add(lblCinema, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 50, 300, 70));

        pnlEntrada.setBackground(new java.awt.Color(102, 0, 0));

        lblEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/entrada.png"))); // NOI18N

        javax.swing.GroupLayout pnlEntradaLayout = new javax.swing.GroupLayout(pnlEntrada);
        pnlEntrada.setLayout(pnlEntradaLayout);
        pnlEntradaLayout.setHorizontalGroup(
            pnlEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEntradaLayout.createSequentialGroup()
                .addContainerGap(316, Short.MAX_VALUE)
                .addComponent(lblEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
        );
        pnlEntradaLayout.setVerticalGroup(
            pnlEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAsientos.add(pnlEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 890, -1));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSalir.setText("SALIR");
        pnlAsientos.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 810, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void rellenarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tblAsientos.getModel();
        
        int columnas = modelo.getColumnCount();
        char fila = '\u0000';
        for(int i = 0; i < columnas; i++){
            fila = modelo.getColumnName(i).charAt(0);
            int contador = 0;
            for(Asiento a : listaAsientos){
                if(a.getFila_asiento() == fila){
                    modelo.setValueAt(a.getNumero_asiento(), contador, i);
                    contador++;
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogAsientos dialog = new DialogAsientos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsientos;
    private javax.swing.JLabel lblAsientosLibres;
    private javax.swing.JLabel lblCinema;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblHorarioPelicula;
    private javax.swing.JLabel lblNombrePelicula;
    private javax.swing.JLabel lblNroSala;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblSala;
    private javax.swing.JPanel pnlAsientos;
    private javax.swing.JPanel pnlEntrada;
    private javax.swing.JPanel pnlPantalla;
    private javax.swing.JTable tblAsientos;
    // End of variables declaration//GEN-END:variables
}
