/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasAdministrativo;

import Controlador.AsientoDAO;
import Modelo.Asiento;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enzo_2
 */
public class DialogAsientos extends javax.swing.JDialog {

    /**
     * Creates new form DialogAsientos
     */
     
    AsientoDAO maniAsi = new AsientoDAO();
    List<Asiento> listaAsientos = maniAsi.listarAsientosPorSala(1);
    
    public DialogAsientos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rellenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        pnlAsientos = new javax.swing.JPanel();
        lblCinema = new javax.swing.JLabel();
        lblSala = new javax.swing.JLabel();
        lblNroSala = new javax.swing.JLabel();
        lblNombrePelicula = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        lblHorarioInicio = new javax.swing.JLabel();
        lblEmpieza = new javax.swing.JLabel();
        lblAsientos = new javax.swing.JLabel();
        lblAsientosLibres = new javax.swing.JLabel();
        lblFinaliza = new javax.swing.JLabel();
        lblHorarioFin = new javax.swing.JLabel();
        lblTipoPelicula = new javax.swing.JLabel();
        lblEsTipo = new javax.swing.JLabel();
        lblIdioma = new javax.swing.JLabel();
        lblIdiomaPelicula = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblGeneroPelicula = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        lblEstadoSub = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsientos = new javax.swing.JTable();
        pnlPantalla = new javax.swing.JPanel();
        lblPantalla = new javax.swing.JLabel();
        pnlEntrada = new javax.swing.JPanel();
        lblEntrada = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlAsientos.setBackground(new java.awt.Color(102, 0, 0));
        pnlAsientos.setForeground(new java.awt.Color(102, 0, 0));
        pnlAsientos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCinema.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblCinema.setForeground(new java.awt.Color(255, 255, 255));
        lblCinema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCinema.setText("CinemaCentro");
        lblCinema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlAsientos.add(lblCinema, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 35, -1, 30));

        lblSala.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblSala.setForeground(new java.awt.Color(255, 255, 255));
        lblSala.setText("SALA N°:");
        pnlAsientos.add(lblSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, -1));

        lblNroSala.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblNroSala.setForeground(new java.awt.Color(255, 255, 255));
        lblNroSala.setText("NUMEROSALA");
        pnlAsientos.add(lblNroSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 6, -1, -1));

        lblNombrePelicula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblNombrePelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePelicula.setText("NOMBREPELICULA");
        pnlAsientos.add(lblNombrePelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 6, -1, -1));

        lblPelicula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblPelicula.setText("PELICULA:");
        pnlAsientos.add(lblPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 6, -1, -1));

        lblHorarioInicio.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblHorarioInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblHorarioInicio.setText("HORARIOINICIO");
        pnlAsientos.add(lblHorarioInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 29, -1, -1));

        lblEmpieza.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblEmpieza.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpieza.setText("EMPIEZA:");
        pnlAsientos.add(lblEmpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 29, -1, -1));

        lblAsientos.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblAsientos.setForeground(new java.awt.Color(255, 255, 255));
        lblAsientos.setText("ASIENTOS:");
        pnlAsientos.add(lblAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 29, -1, -1));

        lblAsientosLibres.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblAsientosLibres.setForeground(new java.awt.Color(255, 255, 255));
        lblAsientosLibres.setText("ASIENTOSLIBRES");
        pnlAsientos.add(lblAsientosLibres, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 29, -1, -1));

        lblFinaliza.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblFinaliza.setForeground(new java.awt.Color(255, 255, 255));
        lblFinaliza.setText("FINALIZA:");
        pnlAsientos.add(lblFinaliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 29, -1, -1));

        lblHorarioFin.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblHorarioFin.setForeground(new java.awt.Color(255, 255, 255));
        lblHorarioFin.setText("HORARIOFINAL");
        pnlAsientos.add(lblHorarioFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 29, -1, -1));

        lblTipoPelicula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblTipoPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoPelicula.setText("ES 2D/3D:");
        pnlAsientos.add(lblTipoPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 6, -1, -1));

        lblEsTipo.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblEsTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblEsTipo.setText("ES2D/3D");
        pnlAsientos.add(lblEsTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 6, -1, -1));

        lblIdioma.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblIdioma.setForeground(new java.awt.Color(255, 255, 255));
        lblIdioma.setText("IDIOMA:");
        pnlAsientos.add(lblIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 52, -1, -1));

        lblIdiomaPelicula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblIdiomaPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblIdiomaPelicula.setText("IDIOMAPELICULA");
        pnlAsientos.add(lblIdiomaPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 52, -1, -1));

        lblGenero.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setText("GENERO:");
        pnlAsientos.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 52, -1, -1));

        lblGeneroPelicula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblGeneroPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblGeneroPelicula.setText("GENEROPELICULA");
        pnlAsientos.add(lblGeneroPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 52, -1, -1));

        lblSub.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblSub.setForeground(new java.awt.Color(255, 255, 255));
        lblSub.setText("SUBTITULADA:");
        pnlAsientos.add(lblSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 6, -1, -1));

        lblEstadoSub.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblEstadoSub.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoSub.setText("SI/NO");
        pnlAsientos.add(lblEstadoSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 6, -1, -1));

        tblAsientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "A", "B", "C", "D", "E", "F", "G", "H", "I", "J"
            }
        ));
        tblAsientos.setCellSelectionEnabled(true);
        tblAsientos.setRowHeight(23);
        jScrollPane1.setViewportView(tblAsientos);

        pnlAsientos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 970, 560));

        pnlPantalla.setBackground(new java.awt.Color(102, 0, 0));
        pnlPantalla.setForeground(new java.awt.Color(255, 255, 255));

        lblPantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pantalla.png"))); // NOI18N
        lblPantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlPantallaLayout = new javax.swing.GroupLayout(pnlPantalla);
        pnlPantalla.setLayout(pnlPantallaLayout);
        pnlPantallaLayout.setHorizontalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPantalla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPantallaLayout.setVerticalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addComponent(lblPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlAsientos.add(pnlPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 163, -1, -1));

        pnlEntrada.setBackground(new java.awt.Color(102, 0, 0));

        lblEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/entrada.png"))); // NOI18N
        lblEntrada.setMaximumSize(new java.awt.Dimension(200, 50));
        lblEntrada.setMinimumSize(new java.awt.Dimension(200, 50));
        lblEntrada.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout pnlEntradaLayout = new javax.swing.GroupLayout(pnlEntrada);
        pnlEntrada.setLayout(pnlEntradaLayout);
        pnlEntradaLayout.setHorizontalGroup(
            pnlEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEntradaLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(lblEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        pnlEntradaLayout.setVerticalGroup(
            pnlEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEntradaLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(lblEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlAsientos.add(pnlEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 23));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlAsientos.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 680, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed
    
    public void rellenarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tblAsientos.getModel();
        
        int columnas = modelo.getColumnCount();
        char fila = '\u0000';
        for(int i = 0; i < columnas; i++){
            fila = modelo.getColumnName(i).charAt(0);
            int contador = 0;
            for(Asiento a : listaAsientos){
                if(a.getFila_asiento() == fila){
                    modelo.setValueAt(a.getNumero_asiento(), contador, i);
                    contador++;
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogAsientos dialog = new DialogAsientos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsientos;
    private javax.swing.JLabel lblAsientosLibres;
    private javax.swing.JLabel lblCinema;
    private javax.swing.JLabel lblEmpieza;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblEsTipo;
    private javax.swing.JLabel lblEstadoSub;
    private javax.swing.JLabel lblFinaliza;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblGeneroPelicula;
    private javax.swing.JLabel lblHorarioFin;
    private javax.swing.JLabel lblHorarioInicio;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblIdiomaPelicula;
    private javax.swing.JLabel lblNombrePelicula;
    private javax.swing.JLabel lblNroSala;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblSala;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblTipoPelicula;
    private javax.swing.JPanel pnlAsientos;
    private javax.swing.JPanel pnlEntrada;
    private javax.swing.JPanel pnlPantalla;
    private javax.swing.JTable tblAsientos;
    // End of variables declaration//GEN-END:variables
}
