/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasAdministrativo;

import Controlador.FuncionDAO;
import Controlador.PeliculaDAO;
import Controlador.SalaDAO;
import Modelo.Funcion;
import Modelo.Pelicula;
import Modelo.Sala;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enzo_2
 */
public class FuncionesInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form FuncionesInternal
     */
    String[] cabeceras = {"id_pelicula", "Titulo"};
    private PeliculaDAO peliculaDAO = new PeliculaDAO();

    String[] cabecerass = {"Sala"};
    private SalaDAO salaDAO = new SalaDAO();

    String[] cabeceraa = {"Horarios inicio", "Horarios fin"};
    private FuncionDAO funciondao = new FuncionDAO();

    public FuncionesInternal() {
        initComponents();
        tblpeliculas.setModel(VentanaAdministrativo.armarCabeceras(cabeceras));
        jTableSala.setModel(VentanaAdministrativo.armarCabeceras(cabecerass));
        jTableHorarios.setModel(VentanaAdministrativo.armarCabeceras(cabeceraa));
        rellenarTablaPelicula();
        rellenarTablaSala();
        rellenartablaHorario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlFunciones = new javax.swing.JPanel();
        lblCinemaCentro = new javax.swing.JLabel();
        lblFunciones = new javax.swing.JLabel();
        lblHorarios = new javax.swing.JLabel();
        lblSala = new javax.swing.JLabel();
        scrollPanePeliculas = new javax.swing.JScrollPane();
        tblpeliculas = new javax.swing.JTable();
        scrollPaneSala = new javax.swing.JScrollPane();
        jTableSala = new javax.swing.JTable();
        scrollPaneHorarios = new javax.swing.JScrollPane();
        jTableHorarios = new javax.swing.JTable();
        lblDescripcionFuncion = new javax.swing.JLabel();
        scrollPaneDesc = new javax.swing.JScrollPane();
        jtableDescripcion = new javax.swing.JTable();
        lblTipoPelicula = new javax.swing.JLabel();
        jRadioButton2D = new javax.swing.JRadioButton();
        jRadioButton3D = new javax.swing.JRadioButton();
        lblIdioma = new javax.swing.JLabel();
        jComboBoxIdioma = new javax.swing.JComboBox<>();
        lblPelicula = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btndarbaja = new javax.swing.JButton();
        lblSubtitulada = new javax.swing.JLabel();
        jComboBoxSubtitulada = new javax.swing.JComboBox<>();
        txtFechaFuncion = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblEstadoFuncion = new javax.swing.JLabel();

        pnlFunciones.setBackground(new java.awt.Color(102, 0, 0));

        lblCinemaCentro.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblCinemaCentro.setForeground(new java.awt.Color(255, 255, 255));
        lblCinemaCentro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCinemaCentro.setText("CinemaCentro");

        lblFunciones.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblFunciones.setForeground(new java.awt.Color(255, 255, 255));
        lblFunciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFunciones.setText("Registrar Funciones");

        lblHorarios.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblHorarios.setForeground(new java.awt.Color(255, 255, 255));
        lblHorarios.setText("Horarios:");

        lblSala.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblSala.setForeground(new java.awt.Color(255, 255, 255));
        lblSala.setText("Sala:");

        tblpeliculas.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        tblpeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollPanePeliculas.setViewportView(tblpeliculas);

        jTableSala.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTableSala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollPaneSala.setViewportView(jTableSala);

        jTableHorarios.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTableHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollPaneHorarios.setViewportView(jTableHorarios);

        lblDescripcionFuncion.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblDescripcionFuncion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionFuncion.setText("Descripción de la Función:");

        jtableDescripcion.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jtableDescripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollPaneDesc.setViewportView(jtableDescripcion);

        lblTipoPelicula.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblTipoPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoPelicula.setText("Tipo:");

        buttonGroup1.add(jRadioButton2D);
        jRadioButton2D.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jRadioButton2D.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2D.setText("2D");
        jRadioButton2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2DActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3D);
        jRadioButton3D.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jRadioButton3D.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3D.setText("3D");

        lblIdioma.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblIdioma.setForeground(new java.awt.Color(255, 255, 255));
        lblIdioma.setText("Idioma:");

        jComboBoxIdioma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxIdioma.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés" }));
        jComboBoxIdioma.setSelectedIndex(-1);
        jComboBoxIdioma.setToolTipText("Elija idioma");
        jComboBoxIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdiomaActionPerformed(evt);
            }
        });

        lblPelicula.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblPelicula.setText("Peliculas:");

        btnConfirmar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnConfirmar.setText("Confirmar");

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/modificar.png"))); // NOI18N

        btndarbaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/dar-baja.png"))); // NOI18N

        lblSubtitulada.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblSubtitulada.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitulada.setText("Subtitulada:");

        jComboBoxSubtitulada.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxSubtitulada.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxSubtitulada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés" }));
        jComboBoxSubtitulada.setSelectedIndex(-1);
        jComboBoxSubtitulada.setToolTipText("Elija idioma");
        jComboBoxSubtitulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSubtituladaActionPerformed(evt);
            }
        });

        txtFechaFuncion.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtFechaFuncion.setText("yyyy-MM-dd");
        txtFechaFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFuncionActionPerformed(evt);
            }
        });

        lblFecha.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha de Función:");

        lblEstado.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setText("Estado:");

        lblEstadoFuncion.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblEstadoFuncion.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoFuncion.setText("ESTADOFUNCION");

        javax.swing.GroupLayout pnlFuncionesLayout = new javax.swing.GroupLayout(pnlFunciones);
        pnlFunciones.setLayout(pnlFuncionesLayout);
        pnlFuncionesLayout.setHorizontalGroup(
            pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFuncionesLayout.createSequentialGroup()
                        .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPelicula)
                            .addComponent(scrollPanePeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneSala, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSala))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFuncionesLayout.createSequentialGroup()
                                .addComponent(lblHorarios)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFuncionesLayout.createSequentialGroup()
                                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scrollPaneHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lblFunciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFuncionesLayout.createSequentialGroup()
                                        .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlFuncionesLayout.createSequentialGroup()
                                                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblEstado)
                                                    .addComponent(lblFecha))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lblEstadoFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtFechaFuncion)))
                                            .addGroup(pnlFuncionesLayout.createSequentialGroup()
                                                .addComponent(lblIdioma)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlFuncionesLayout.createSequentialGroup()
                                                .addComponent(lblSubtitulada)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxSubtitulada, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFuncionesLayout.createSequentialGroup()
                                        .addComponent(lblTipoPelicula)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton2D)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton3D)
                                        .addGap(58, 58, 58))))))
                    .addGroup(pnlFuncionesLayout.createSequentialGroup()
                        .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFuncionesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCinemaCentro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnConfirmar, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(scrollPaneDesc)
                            .addGroup(pnlFuncionesLayout.createSequentialGroup()
                                .addComponent(lblDescripcionFuncion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btndarbaja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btneliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnmodificar)))
                        .addContainerGap())))
        );
        pnlFuncionesLayout.setVerticalGroup(
            pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncionesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCinemaCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFunciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFuncionesLayout.createSequentialGroup()
                        .addComponent(lblHorarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlFuncionesLayout.createSequentialGroup()
                                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIdioma)
                                    .addComponent(jComboBoxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSubtitulada)
                                    .addComponent(jComboBoxSubtitulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTipoPelicula)
                                    .addComponent(jRadioButton2D)
                                    .addComponent(jRadioButton3D))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFechaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFecha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEstado)
                                    .addComponent(lblEstadoFuncion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btndarbaja)
                                    .addComponent(btneliminar)
                                    .addComponent(btnmodificar)))
                            .addGroup(pnlFuncionesLayout.createSequentialGroup()
                                .addComponent(scrollPaneHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(lblDescripcionFuncion))))
                    .addGroup(pnlFuncionesLayout.createSequentialGroup()
                        .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPelicula)
                            .addComponent(lblSala))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPanePeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPaneSala, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFunciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFunciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2DActionPerformed

    private void jComboBoxIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIdiomaActionPerformed

    private void jComboBoxSubtituladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSubtituladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSubtituladaActionPerformed

    private void txtFechaFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFuncionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFuncionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btndarbaja;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBoxIdioma;
    private javax.swing.JComboBox<String> jComboBoxSubtitulada;
    private javax.swing.JRadioButton jRadioButton2D;
    private javax.swing.JRadioButton jRadioButton3D;
    private javax.swing.JTable jTableHorarios;
    private javax.swing.JTable jTableSala;
    private javax.swing.JTable jtableDescripcion;
    private javax.swing.JLabel lblCinemaCentro;
    private javax.swing.JLabel lblDescripcionFuncion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoFuncion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFunciones;
    private javax.swing.JLabel lblHorarios;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblSala;
    private javax.swing.JLabel lblSubtitulada;
    private javax.swing.JLabel lblTipoPelicula;
    private javax.swing.JPanel pnlFunciones;
    private javax.swing.JScrollPane scrollPaneDesc;
    private javax.swing.JScrollPane scrollPaneHorarios;
    private javax.swing.JScrollPane scrollPanePeliculas;
    private javax.swing.JScrollPane scrollPaneSala;
    private javax.swing.JTable tblpeliculas;
    private javax.swing.JTextField txtFechaFuncion;
    // End of variables declaration//GEN-END:variables

    private void rellenarTablaPelicula() {

        try {
            List<Pelicula> pelis = peliculaDAO.listarTodasPeliculas();
            DefaultTableModel model = VentanaAdministrativo.armarCabeceras(cabeceras);
            for (Pelicula p : pelis) {
                model.addRow(new Object[]{
                    p.getId_Pelicula(),
                    p.getTitulo()
                });
            }
            tblpeliculas.setModel(model);
            ocultarID();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla peliculas: " );
        }
    }

    private void rellenarTablaSala() {
        try {
            List<Sala> salas = salaDAO.listarsalas();
            DefaultTableModel model = VentanaAdministrativo.armarCabeceras(cabecerass);
            for (Sala s : salas) {
                model.addRow(new Object[]{
                    s.getNro_Sala()
                });
            }
            jTableSala.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla salas : " );
        }
    }

    private void rellenartablaHorario() {
        try {
            List<Funcion> funci = funciondao.listarFunciones();
            DefaultTableModel model = VentanaAdministrativo.armarCabeceras(cabeceraa);
            for (Funcion f : funci) {
                model.addRow(new Object[]{
                    f.getHora_Inicio(),
                    f.getHora_Fin()
                });
            }
            jTableHorarios.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla horarios: ");
        }
    }

    private void ocultarID(){
        if (tblpeliculas.getColumnCount() > 0) {
            tblpeliculas.getColumnModel().getColumn(0).setMinWidth(0);
            tblpeliculas.getColumnModel().getColumn(0).setMaxWidth(0);
            tblpeliculas.getColumnModel().getColumn(0).setWidth(0);
        }
    }
}
