/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasAdministrativo;

import Controlador.AsientoDAO;
import Controlador.FuncionDAO;
import Controlador.PeliculaDAO;
import Modelo.Asiento;
import Modelo.Funcion;
import Modelo.Pelicula;
import Modelo.Venta;
import VistasCliente.DialogCompra;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Enzo_2
 */
public class TaquillaInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form TaquillaInternal
     */
    PeliculaDAO maniPeli = new PeliculaDAO();
    FuncionDAO maniFuncion = new FuncionDAO();
    AsientoDAO maniAsi = new AsientoDAO();
    String[] cabeceraCartelera = {"id_pelicula", "Titulo", "Director", "Reparto", "Pais de origen", "Genero/s"};
    String[] cabeceraFunciones = {"id_funcion", "Número de sala", "Idioma", "3D", "Hora de inicio", "Hora finalización", "Precio de entrada",
        "Fecha de función", "Subtitulada"};
    List<Pelicula> listaCartelera = maniPeli.listarPeliculasEnCartelera();
    List<Funcion> listaFuncionPorPelicula;
    List<Asiento> listaAsientos = new ArrayList<>();
    DefaultListModel<String> modeloLista;
    int id_peliculaS = -1;
    int id_funcion = -1;
    int nro_sala = -1;
    double precioEntrada = 0;
    double precioTotal = 0;
    boolean estadoExito;

    public TaquillaInternal() {
        initComponents();
        modeloLista = new DefaultListModel<>();
        listAsientosS.setModel(modeloLista);
        txtCantidadBoletos.setEnabled(false);
        tblCartelera.setModel(VentanaAdministrativo.armarCabeceras(cabeceraCartelera));
        tblFunciones.setModel(VentanaAdministrativo.armarCabeceras(cabeceraFunciones));
        ocultarIDs();
        rellenarTablaPelicula();
        agregarListenerCartelera();
        agregarListenerFunciones();

        cmbMedioPago.addItem("...");
        cmbMedioPago.addItem("Efectivo");
        cmbMedioPago.addItem("Debito");
        cmbMedioPago.setSelectedIndex(0);

        cmbMedioPago.addActionListener(e -> {
            String medio = mediodePago();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTaquilla = new javax.swing.JPanel();
        lblCarteleraActual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCartelera = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFunciones = new javax.swing.JTable();
        lblFuncionesxPelicula = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        lblPrecioEntradaIndividual = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPeliculaS = new javax.swing.JLabel();
        lblGeneros = new javax.swing.JLabel();
        lblGenerosS = new javax.swing.JLabel();
        lblNumeroSala = new javax.swing.JLabel();
        lblidioma = new javax.swing.JLabel();
        lbl3D = new javax.swing.JLabel();
        lblHorarioInicio = new javax.swing.JLabel();
        lblHorarioFin = new javax.swing.JLabel();
        lblNumeroSalaS = new javax.swing.JLabel();
        lblIdiomaS = new javax.swing.JLabel();
        lbl3DS = new javax.swing.JLabel();
        lblHorarioInicioS = new javax.swing.JLabel();
        lblHorarioFinS = new javax.swing.JLabel();
        lblFechaFuncion = new javax.swing.JLabel();
        lblSubtitulada = new javax.swing.JLabel();
        lblSubtituladaS = new javax.swing.JLabel();
        txtCantidadBoletos = new javax.swing.JTextField();
        lblCantidadBoletos = new javax.swing.JLabel();
        lblFechaS = new javax.swing.JLabel();
        lblPrecioEntradaIndividualS = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listAsientosS = new javax.swing.JList<>();
        btnConfirmacion = new javax.swing.JButton();
        lblAsientosSeleccionados = new javax.swing.JLabel();
        lblImporteT = new javax.swing.JLabel();
        lblImporteTotal = new javax.swing.JLabel();
        btnRealizarCompra = new javax.swing.JButton();
        btnCancelarAsientos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cmbMedioPago = new javax.swing.JComboBox<>();
        lblMedioPago = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblCinemaCentro = new javax.swing.JLabel();

        pnlTaquilla.setBackground(new java.awt.Color(102, 0, 0));

        lblCarteleraActual.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblCarteleraActual.setForeground(new java.awt.Color(255, 255, 255));
        lblCarteleraActual.setText("Cartelera:");

        tblCartelera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCartelera);

        tblFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblFunciones);

        lblFuncionesxPelicula.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblFuncionesxPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblFuncionesxPelicula.setText("Funciones:");

        lblPelicula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblPelicula.setText("Película:");

        lblPrecioEntradaIndividual.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblPrecioEntradaIndividual.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioEntradaIndividual.setText("Precio de Entrada:");

        lblPeliculaS.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        lblPeliculaS.setForeground(new java.awt.Color(255, 255, 255));

        lblGeneros.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblGeneros.setForeground(new java.awt.Color(255, 255, 255));
        lblGeneros.setText("Género/s:");

        lblGenerosS.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        lblGenerosS.setForeground(new java.awt.Color(255, 255, 255));

        lblNumeroSala.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblNumeroSala.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroSala.setText("Número de Sala:");

        lblidioma.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblidioma.setForeground(new java.awt.Color(255, 255, 255));
        lblidioma.setText("Idioma:");

        lbl3D.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lbl3D.setForeground(new java.awt.Color(255, 255, 255));
        lbl3D.setText("Apta 3D:");

        lblHorarioInicio.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblHorarioInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblHorarioInicio.setText("Horario de Inicio:");

        lblHorarioFin.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblHorarioFin.setForeground(new java.awt.Color(255, 255, 255));
        lblHorarioFin.setText("Horario de Finalización:");

        lblNumeroSalaS.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        lblNumeroSalaS.setForeground(new java.awt.Color(255, 255, 255));

        lblIdiomaS.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        lblIdiomaS.setForeground(new java.awt.Color(255, 255, 255));

        lbl3DS.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        lbl3DS.setForeground(new java.awt.Color(255, 255, 255));

        lblHorarioInicioS.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        lblHorarioInicioS.setForeground(new java.awt.Color(255, 255, 255));

        lblHorarioFinS.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        lblHorarioFinS.setForeground(new java.awt.Color(255, 255, 255));

        lblFechaFuncion.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblFechaFuncion.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaFuncion.setText("Fecha de la Función:");

        lblSubtitulada.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblSubtitulada.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitulada.setText("Subtitulada:");

        lblSubtituladaS.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        lblSubtituladaS.setForeground(new java.awt.Color(255, 255, 255));

        txtCantidadBoletos.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        txtCantidadBoletos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadBoletosKeyReleased(evt);
            }
        });

        lblCantidadBoletos.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblCantidadBoletos.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadBoletos.setText("Cantidad de Boletos:");

        lblFechaS.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        lblFechaS.setForeground(new java.awt.Color(255, 255, 255));

        lblPrecioEntradaIndividualS.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        lblPrecioEntradaIndividualS.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setViewportView(listAsientosS);

        btnConfirmacion.setBackground(new java.awt.Color(70, 73, 75));
        btnConfirmacion.setFont(new java.awt.Font("Roboto Black", 1, 13)); // NOI18N
        btnConfirmacion.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmacion.setText("Seleccionar asientos");
        btnConfirmacion.setEnabled(false);
        btnConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmacionActionPerformed(evt);
            }
        });

        lblAsientosSeleccionados.setFont(new java.awt.Font("Roboto Black", 1, 13)); // NOI18N
        lblAsientosSeleccionados.setForeground(new java.awt.Color(255, 255, 255));
        lblAsientosSeleccionados.setText("Asientos Seleccionados:");

        lblImporteT.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblImporteT.setForeground(new java.awt.Color(255, 255, 255));
        lblImporteT.setText("Importe Total:");

        lblImporteTotal.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        lblImporteTotal.setForeground(new java.awt.Color(255, 255, 255));

        btnRealizarCompra.setBackground(new java.awt.Color(70, 73, 75));
        btnRealizarCompra.setFont(new java.awt.Font("Roboto Black", 1, 13)); // NOI18N
        btnRealizarCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizarCompra.setText("Realizar Compra");
        btnRealizarCompra.setEnabled(false);
        btnRealizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarCompraActionPerformed(evt);
            }
        });

        btnCancelarAsientos.setBackground(new java.awt.Color(70, 73, 75));
        btnCancelarAsientos.setFont(new java.awt.Font("Roboto Black", 1, 13)); // NOI18N
        btnCancelarAsientos.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarAsientos.setText("Cancelar Asientos");
        btnCancelarAsientos.setEnabled(false);
        btnCancelarAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAsientosActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(70, 73, 75));
        btnSalir.setFont(new java.awt.Font("Roboto Black", 1, 13)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        cmbMedioPago.setForeground(new java.awt.Color(255, 255, 255));
        cmbMedioPago.setEnabled(false);

        lblMedioPago.setFont(new java.awt.Font("Roboto Black", 1, 13)); // NOI18N
        lblMedioPago.setForeground(new java.awt.Color(255, 255, 255));
        lblMedioPago.setText("Medio de Pago:");

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("TAQUILLA");

        lblCinemaCentro.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblCinemaCentro.setForeground(new java.awt.Color(255, 255, 255));
        lblCinemaCentro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCinemaCentro.setText("CinemaCentro");

        javax.swing.GroupLayout pnlTaquillaLayout = new javax.swing.GroupLayout(pnlTaquilla);
        pnlTaquilla.setLayout(pnlTaquillaLayout);
        pnlTaquillaLayout.setHorizontalGroup(
            pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaquillaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFuncionesxPelicula)
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                                        .addComponent(lblNumeroSala)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblNumeroSalaS, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                                        .addComponent(lblGeneros)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblGenerosS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                                        .addComponent(lbl3D)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lbl3DS, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTaquillaLayout.createSequentialGroup()
                                                            .addComponent(lblSubtitulada)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(lblSubtituladaS, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTaquillaLayout.createSequentialGroup()
                                                            .addComponent(lblidioma)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(lblIdiomaS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addGap(23, 23, 23))))
                                                .addGap(47, 47, 47)
                                                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                                                    .addComponent(lblHorarioFin)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(lblHorarioFinS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                                                    .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(lblPrecioEntradaIndividual)
                                                                        .addComponent(lblHorarioInicio))
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblHorarioInicioS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaquillaLayout.createSequentialGroup()
                                                                            .addComponent(lblPrecioEntradaIndividualS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addGap(5, 5, 5)))))
                                                            .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(lblCantidadBoletos)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtCantidadBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                                                .addGap(69, 69, 69)
                                                                .addComponent(btnConfirmacion)))
                                                        .addGap(33, 33, 33))
                                                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                                        .addComponent(lblFechaFuncion)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblFechaS, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTaquillaLayout.createSequentialGroup()
                                                        .addGap(57, 57, 57)
                                                        .addComponent(lblImporteT)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                                .addComponent(lblPelicula)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblPeliculaS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAsientosSeleccionados)
                                            .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cmbMedioPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnSalir)
                                                .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnRealizarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnCancelarAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                    .addComponent(lblCarteleraActual))
                                .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                    .addComponent(lblTitulo)
                                    .addGap(134, 134, 134)
                                    .addComponent(lblCinemaCentro))))))
                .addGap(11, 11, 11))
        );
        pnlTaquillaLayout.setVerticalGroup(
            pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaquillaLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblCinemaCentro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCarteleraActual)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFuncionesxPelicula)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblPelicula))
                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblPeliculaS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaquillaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAsientosSeleccionados)
                            .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPrecioEntradaIndividual)
                                .addComponent(lblPrecioEntradaIndividualS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHorarioInicio)
                                    .addComponent(lblHorarioInicioS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHorarioFin)
                                    .addComponent(lblHorarioFinS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(lblFechaFuncion)
                                        .addGap(2, 2, 2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaquillaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFechaS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))))
                            .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblMedioPago)
                                .addGap(6, 6, 6)
                                .addComponent(cmbMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCantidadBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCantidadBoletos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblImporteT))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirmacion))
                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                        .addComponent(btnRealizarCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarAsientos))
                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                .addComponent(lblGeneros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumeroSala)
                                    .addComponent(lblNumeroSalaS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblGenerosS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblidioma)
                            .addComponent(lblIdiomaS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl3D)
                            .addComponent(lbl3DS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtitulada)
                            .addComponent(lblSubtituladaS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTaquilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTaquilla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmacionActionPerformed

        try {
            int cantidad = Integer.parseInt(txtCantidadBoletos.getText());
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "Ingrese una cantidad mayor a 0.");
                return;
            }
            listaAsientos = new ArrayList<>();
            JFrame padre = (JFrame) SwingUtilities.getWindowAncestor(this);
            for (int i = 0; i < cantidad; i++) {
                DialogAsientos ventanaAsientos = new DialogAsientos(padre, true, nro_sala);
                ventanaAsientos.setVisible(true);
                Asiento asientoS = ventanaAsientos.getAsientoSeleccionado();

                if (asientoS != null) {
                    modeloLista.addElement(String.valueOf(asientoS.getFila_asiento()) + "-" + asientoS.getNumero_asiento());
                    listaAsientos.add(asientoS);

                    listAsientosS.setOpaque(true);
                    btnCancelarAsientos.setEnabled(true);
                    cmbMedioPago.setEnabled(true);

                    System.out.println(asientoS.toString());
                } else {

                    btnConfirmacion.setEnabled(true);
                    btnCancelarAsientos.setEnabled(false);
                    JOptionPane.showMessageDialog(this, "Cancelada selección de boletos");

                    for (Asiento a : listaAsientos) {
                        try {
                            maniAsi.darAlta(a.getId_asiento());
                        } catch (Exception e) {
                            System.out.println("Error al dar de alta nuevamente.");
                        }
                    }
                    modeloLista.clear();
                    listaAsientos.clear();
                    break;
                }
                btnConfirmacion.setEnabled(false);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un numero valido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnConfirmacionActionPerformed

    private void btnCancelarAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAsientosActionPerformed
        modeloLista.clear();
        for (Asiento a : listaAsientos) {
            try {
                maniAsi.darAlta(a.getId_asiento());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        cmbMedioPago.setSelectedIndex(0);
        txtCantidadBoletos.setText("");
        btnConfirmacion.setEnabled(false);
        btnCancelarAsientos.setEnabled(false);
        btnRealizarCompra.setEnabled(false);
        cmbMedioPago.setEnabled(false);
        listAsientosS.setOpaque(false);
    }//GEN-LAST:event_btnCancelarAsientosActionPerformed

    private void txtCantidadBoletosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadBoletosKeyReleased
        String cantidadBoletos = txtCantidadBoletos.getText();
        try {
            int cantidad = Integer.parseInt(cantidadBoletos);
            precioTotal = precioEntrada * cantidad;
            lblImporteTotal.setText(Double.toString(precioTotal));

            btnConfirmacion.setEnabled(true);
        } catch (NumberFormatException e) {
            lblImporteTotal.setText("0");
        } catch (Exception a) {
            JOptionPane.showMessageDialog(this, a.getMessage());
        }
    }//GEN-LAST:event_txtCantidadBoletosKeyReleased

    private void btnRealizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarCompraActionPerformed
        Venta venta = new Venta();
        venta.setMedio_Pago(mediodePago());
        venta.setCantidad_Entradas(Integer.parseInt(txtCantidadBoletos.getText()));
        venta.setImporte_Total(precioTotal);
        venta.setMedio_Compra("Taquilla");
        venta.setFecha_Venta(LocalDate.now());

        try {
            JFrame padre = (JFrame) SwingUtilities.getWindowAncestor(this);
            DialogCompra ventanaCompra = new DialogCompra(padre, true, listaAsientos, venta, mediodePago(), id_funcion, "taquilla");
            ventanaCompra.setVisible(true);
            estadoExito = ventanaCompra.isEstado();

            if (!estadoExito) {
                for (Asiento a : listaAsientos) {
                    try {
                        maniAsi.darBaja(a.getId_asiento());
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                }
                tblCartelera.clearSelection();
                tblFunciones.clearSelection();
                listaAsientos.clear();
                cmbMedioPago.setSelectedIndex(0);
            }
        } catch (NullPointerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "No tiene seleccionados los asientos a comprar o no tiene seleccionado un medio de pago.");

        } catch (Exception ex) {
            Logger.getLogger(TaquillaInternal.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiarCampos();
    }//GEN-LAST:event_btnRealizarCompraActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if (listaAsientos.isEmpty() || listaAsientos == null) {
            this.dispose();
        } else {
            int eleccion = JOptionPane.showConfirmDialog(this, "Selección de butacas en curso. ¿Esta seguro que desea salir? Se perderan los datos ingresados.","Error", YES_NO_OPTION);
            if(eleccion == 0){
                modeloLista.clear();
                for(Asiento a : listaAsientos){
                    try{
                        maniAsi.darAlta(a.getId_asiento());
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                }
                this.dispose();
            }
        }


    }//GEN-LAST:event_btnSalirActionPerformed

    public String mediodePago() {
        if (cmbMedioPago.getSelectedIndex() == 0) {
            return "";
        } else if (cmbMedioPago.getSelectedIndex() == 1) {
            btnRealizarCompra.setEnabled(true);
            
            return "Efectivo";
        } else if (cmbMedioPago.getSelectedIndex() == 2) {
            btnRealizarCompra.setEnabled(true);
            return "Debito";
        }
        return "";
    }

    public void ocultarIDs() {

        TableColumnModel modeloColumnasP = tblCartelera.getColumnModel();
        TableColumnModel modeloColumnasF = tblFunciones.getColumnModel();
        TableColumn columnaP = modeloColumnasP.getColumn(0);
        TableColumn columnaF = modeloColumnasF.getColumn(0);
        columnaP.setMaxWidth(0);
        columnaP.setMinWidth(0);
        columnaP.setPreferredWidth(0);
        columnaP.setResizable(false);

        columnaF.setMaxWidth(0);
        columnaF.setMinWidth(0);
        columnaF.setPreferredWidth(0);
        columnaF.setResizable(false);
    }

    public void rellenarTablaPelicula() {
        DefaultTableModel modelo = (DefaultTableModel) tblCartelera.getModel();
        modelo.setRowCount(0);
        for (Pelicula p : listaCartelera) {
            modelo.addRow(new Object[]{p.getId_Pelicula(),
                p.getTitulo(),
                p.getDirector(),
                p.getReparto(),
                p.getPais_Origen(),
                p.getGenero()
            });
        }
    }

    public void rellenarTablaFunciones(int id_pelicula) {
        DefaultTableModel modelo = (DefaultTableModel) tblFunciones.getModel();
        modelo.setRowCount(0);
        try {
            listaFuncionPorPelicula = maniFuncion.listadoPorId(id_pelicula);

            for (Funcion f : listaFuncionPorPelicula) {
                modelo.addRow(new Object[]{f.getId_Funcion(),
                    f.getNro_Sala(),
                    f.getIdioma(),
                    parsearBoolean(f.isEs3D()),
                    f.getHora_Inicio(),
                    f.getHora_Fin(),
                    f.getPrecio_Entrada(),
                    f.getFecha_Funcion(),
                    parsearBoolean(f.isSubtitulada())
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void agregarListenerCartelera() {
        tblCartelera.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent evento) {
                if (evento.getValueIsAdjusting()) {
                    return;
                }
                int filaS = tblCartelera.getSelectedRow();
                if (filaS != -1) {
                    id_peliculaS = (int) tblCartelera.getValueAt(filaS, 0);
                    rellenarTablaFunciones(id_peliculaS);
                    lblPeliculaS.setText((String) tblCartelera.getValueAt(filaS, 1));
                    lblGenerosS.setText((String) tblCartelera.getValueAt(filaS, 5));

                }
            }
        });
    }

    public void agregarListenerFunciones() {
        tblFunciones.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent evento) {
                if (evento.getValueIsAdjusting()) {
                    return;
                }
                int filaS = tblFunciones.getSelectedRow();
                if (filaS != -1) {
                    nro_sala = (int) tblFunciones.getValueAt(filaS, 1);
                    id_funcion = (int) tblFunciones.getValueAt(filaS, 0);
                    precioEntrada = (double) tblFunciones.getValueAt(filaS, 6);
                    lblNumeroSalaS.setText(Integer.toString((int) tblFunciones.getValueAt(filaS, 1)));
                    lblIdiomaS.setText(tblFunciones.getValueAt(filaS, 2).toString());
                    lbl3DS.setText(tblFunciones.getValueAt(filaS, 3).toString());
                    lblHorarioInicioS.setText(tblFunciones.getValueAt(filaS, 4).toString());
                    lblHorarioFinS.setText(tblFunciones.getValueAt(filaS, 5).toString());
                    lblPrecioEntradaIndividualS.setText(tblFunciones.getValueAt(filaS, 6).toString());
                    lblFechaS.setText(tblFunciones.getValueAt(filaS, 7).toString());
                    lblSubtituladaS.setText(tblFunciones.getValueAt(filaS, 8).toString());
                    txtCantidadBoletos.setEnabled(true);

                } else {
                    lblNumeroSalaS.setText("");
                    lblIdiomaS.setText("");
                    lbl3DS.setText("");
                    lblSubtituladaS.setText("");
                    lblHorarioInicioS.setText("");
                    lblHorarioFinS.setText("");
                    lblFechaS.setText("");
                    txtCantidadBoletos.setEnabled(false);
                }
            }
        });
    }

    private void limpiarCampos() {
        txtCantidadBoletos.setText("");
        btnConfirmacion.setEnabled(false);
        listAsientosS.setOpaque(false);
        btnRealizarCompra.setEnabled(false);
        btnCancelarAsientos.setEnabled(false);
        cmbMedioPago.setEnabled(false);
        id_peliculaS = -1;
        id_funcion = -1;
        nro_sala = -1;
        modeloLista.clear();
        listAsientosS.setModel(modeloLista);
        rellenarTablaFunciones(id_peliculaS);

    }

    public String parsearBoolean(boolean estado) {
        if (estado) {
            return "Si";
        }
        return "No";
    }

    public boolean parsearString(String estado) {
        return estado.equalsIgnoreCase("Si");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarAsientos;
    private javax.swing.JButton btnConfirmacion;
    private javax.swing.JButton btnRealizarCompra;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbMedioPago;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl3D;
    private javax.swing.JLabel lbl3DS;
    private javax.swing.JLabel lblAsientosSeleccionados;
    private javax.swing.JLabel lblCantidadBoletos;
    private javax.swing.JLabel lblCarteleraActual;
    private javax.swing.JLabel lblCinemaCentro;
    private javax.swing.JLabel lblFechaFuncion;
    private javax.swing.JLabel lblFechaS;
    private javax.swing.JLabel lblFuncionesxPelicula;
    private javax.swing.JLabel lblGeneros;
    private javax.swing.JLabel lblGenerosS;
    private javax.swing.JLabel lblHorarioFin;
    private javax.swing.JLabel lblHorarioFinS;
    private javax.swing.JLabel lblHorarioInicio;
    private javax.swing.JLabel lblHorarioInicioS;
    private javax.swing.JLabel lblIdiomaS;
    private javax.swing.JLabel lblImporteT;
    private javax.swing.JLabel lblImporteTotal;
    private javax.swing.JLabel lblMedioPago;
    private javax.swing.JLabel lblNumeroSala;
    private javax.swing.JLabel lblNumeroSalaS;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblPeliculaS;
    private javax.swing.JLabel lblPrecioEntradaIndividual;
    private javax.swing.JLabel lblPrecioEntradaIndividualS;
    private javax.swing.JLabel lblSubtitulada;
    private javax.swing.JLabel lblSubtituladaS;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblidioma;
    private javax.swing.JList<String> listAsientosS;
    private javax.swing.JPanel pnlTaquilla;
    private javax.swing.JTable tblCartelera;
    private javax.swing.JTable tblFunciones;
    private javax.swing.JTextField txtCantidadBoletos;
    // End of variables declaration//GEN-END:variables
}
