/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasAdministrativo;

import javax.swing.JOptionPane;

/**
 *
 * @author Enzo_2
 */
public class TaquillaInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form TaquillaInternal
     */
    public TaquillaInternal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTaquilla = new javax.swing.JPanel();
        lblCarteleraActual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCartelera = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblFuncionesxPelicula = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        lblPrecioEntradaIndividual = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPeliculaS = new javax.swing.JLabel();
        lblGeneros = new javax.swing.JLabel();
        lblGenerosS = new javax.swing.JLabel();
        lblNumeroSala = new javax.swing.JLabel();
        lblidioma = new javax.swing.JLabel();
        lbl3D = new javax.swing.JLabel();
        lblHorarioInicio = new javax.swing.JLabel();
        lblHorarioFin = new javax.swing.JLabel();
        lblNumeroSalaS = new javax.swing.JLabel();
        lblIdiomaS = new javax.swing.JLabel();
        lbl3DS = new javax.swing.JLabel();
        lblHorarioInicioS = new javax.swing.JLabel();
        lblHorarioFinS = new javax.swing.JLabel();
        lblFechaFuncion = new javax.swing.JLabel();
        lblSubtitulada = new javax.swing.JLabel();
        lblSubtituladaS = new javax.swing.JLabel();
        txtCantidadBoletos = new javax.swing.JTextField();
        lblCantidadBoletos = new javax.swing.JLabel();
        lblFechaS = new javax.swing.JLabel();
        lblPrecioEntradaIndividualS = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listAsientosS = new javax.swing.JList<>();
        btnConfirmacion = new javax.swing.JButton();
        lblAsientosSeleccionados = new javax.swing.JLabel();
        lblImporteT = new javax.swing.JLabel();
        lblImporteTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        pnlTaquilla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarteleraActual.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblCarteleraActual.setText("Cartelera actual: ");
        pnlTaquilla.add(lblCarteleraActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tblCartelera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCartelera);

        pnlTaquilla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 33, 861, 140));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        pnlTaquilla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 201, 861, 134));

        lblFuncionesxPelicula.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblFuncionesxPelicula.setText("Funciones disponibles para la pelicula seleccionada");
        pnlTaquilla.add(lblFuncionesxPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lblPelicula.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblPelicula.setText("Pelicula");
        pnlTaquilla.add(lblPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        lblPrecioEntradaIndividual.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblPrecioEntradaIndividual.setText("Precio entrada individual");
        pnlTaquilla.add(lblPrecioEntradaIndividual, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));
        pnlTaquilla.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        lblPeliculaS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        pnlTaquilla.add(lblPeliculaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 130, 20));

        lblGeneros.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblGeneros.setText("Genero/s");
        pnlTaquilla.add(lblGeneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        lblGenerosS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        pnlTaquilla.add(lblGenerosS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 130, 20));

        lblNumeroSala.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblNumeroSala.setText("Número de sala");
        pnlTaquilla.add(lblNumeroSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        lblidioma.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblidioma.setText("Idioma");
        pnlTaquilla.add(lblidioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        lbl3D.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lbl3D.setText("3D");
        pnlTaquilla.add(lbl3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        lblHorarioInicio.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblHorarioInicio.setText("Horario de inicio");
        pnlTaquilla.add(lblHorarioInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        lblHorarioFin.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblHorarioFin.setText("Horario de finalización");
        pnlTaquilla.add(lblHorarioFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        lblNumeroSalaS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        pnlTaquilla.add(lblNumeroSalaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 130, 20));

        lblIdiomaS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        pnlTaquilla.add(lblIdiomaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 120, 20));

        lbl3DS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        pnlTaquilla.add(lbl3DS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 130, 20));

        lblHorarioInicioS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        pnlTaquilla.add(lblHorarioInicioS, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 70, 20));

        lblHorarioFinS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        pnlTaquilla.add(lblHorarioFinS, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 70, 20));

        lblFechaFuncion.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblFechaFuncion.setText("Fecha de la funcion");
        pnlTaquilla.add(lblFechaFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        lblSubtitulada.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblSubtitulada.setText("Subtitulada");
        pnlTaquilla.add(lblSubtitulada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        lblSubtituladaS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        pnlTaquilla.add(lblSubtituladaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 140, 20));
        pnlTaquilla.add(txtCantidadBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 70, -1));

        lblCantidadBoletos.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblCantidadBoletos.setText("Cantidad de boletos");
        pnlTaquilla.add(lblCantidadBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        lblFechaS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        pnlTaquilla.add(lblFechaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 70, 20));

        lblPrecioEntradaIndividualS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        pnlTaquilla.add(lblPrecioEntradaIndividualS, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 70, 20));

        jScrollPane3.setViewportView(listAsientosS);

        pnlTaquilla.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 150, 200));

        btnConfirmacion.setText("Confirmar cantidad de boletos");
        btnConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmacionActionPerformed(evt);
            }
        });
        pnlTaquilla.add(btnConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        lblAsientosSeleccionados.setText("Asientos seleccionados");
        pnlTaquilla.add(lblAsientosSeleccionados, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        lblImporteT.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblImporteT.setText("Importe total");
        pnlTaquilla.add(lblImporteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 130, -1));
        pnlTaquilla.add(lblImporteTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 70, 20));

        jButton1.setText("Realizar compra");
        pnlTaquilla.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTaquilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTaquilla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmacionActionPerformed
        try {
            int cantidad = Integer.parseInt(txtCantidadBoletos.getText());
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Ingrese un numero valido.");
        }
 
    }//GEN-LAST:event_btnConfirmacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl3D;
    private javax.swing.JLabel lbl3DS;
    private javax.swing.JLabel lblAsientosSeleccionados;
    private javax.swing.JLabel lblCantidadBoletos;
    private javax.swing.JLabel lblCarteleraActual;
    private javax.swing.JLabel lblFechaFuncion;
    private javax.swing.JLabel lblFechaS;
    private javax.swing.JLabel lblFuncionesxPelicula;
    private javax.swing.JLabel lblGeneros;
    private javax.swing.JLabel lblGenerosS;
    private javax.swing.JLabel lblHorarioFin;
    private javax.swing.JLabel lblHorarioFinS;
    private javax.swing.JLabel lblHorarioInicio;
    private javax.swing.JLabel lblHorarioInicioS;
    private javax.swing.JLabel lblIdiomaS;
    private javax.swing.JLabel lblImporteT;
    private javax.swing.JLabel lblImporteTotal;
    private javax.swing.JLabel lblNumeroSala;
    private javax.swing.JLabel lblNumeroSalaS;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblPeliculaS;
    private javax.swing.JLabel lblPrecioEntradaIndividual;
    private javax.swing.JLabel lblPrecioEntradaIndividualS;
    private javax.swing.JLabel lblSubtitulada;
    private javax.swing.JLabel lblSubtituladaS;
    private javax.swing.JLabel lblidioma;
    private javax.swing.JList<String> listAsientosS;
    private javax.swing.JPanel pnlTaquilla;
    private javax.swing.JTable tblCartelera;
    private javax.swing.JTextField txtCantidadBoletos;
    // End of variables declaration//GEN-END:variables
}
