/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasAdministrativo;

import Controlador.FuncionDAO;
import Controlador.PeliculaDAO;
import Modelo.Funcion;
import Modelo.Pelicula;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Enzo_2
 */
public class TaquillaInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form TaquillaInternal
     */
    PeliculaDAO maniPeli = new PeliculaDAO();
    FuncionDAO maniFuncion = new FuncionDAO();
    String[] cabeceraCartelera = {"id_pelicula", "Titulo", "Director", "Reparto", "Pais de origen", "Genero/s"};
    String[] cabeceraFunciones = {"id_funcion", "Número de sala", "Idioma", "3D", "Hora de inicio", "Hora finalización", "Precio de entrada",
        "Fecha de función", "Subtitulada"};
    List<Pelicula> listaCartelera = maniPeli.listarPeliculasEnCartelera();
    List<Funcion> listaFuncionPorPelicula;
    int id_peliculaS = -1;
    public TaquillaInternal() {
        initComponents();
        tblCartelera.setModel(VentanaAdministrativo.armarCabeceras(cabeceraCartelera));
        tblFunciones.setModel(VentanaAdministrativo.armarCabeceras(cabeceraFunciones));
        ocultarIDs();
        rellenarTablaPelicula();
        agregarListenerCartelera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTaquilla = new javax.swing.JPanel();
        lblCarteleraActual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCartelera = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFunciones = new javax.swing.JTable();
        lblFuncionesxPelicula = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        lblPrecioEntradaIndividual = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPeliculaS = new javax.swing.JLabel();
        lblGeneros = new javax.swing.JLabel();
        lblGenerosS = new javax.swing.JLabel();
        lblNumeroSala = new javax.swing.JLabel();
        lblidioma = new javax.swing.JLabel();
        lbl3D = new javax.swing.JLabel();
        lblHorarioInicio = new javax.swing.JLabel();
        lblHorarioFin = new javax.swing.JLabel();
        lblNumeroSalaS = new javax.swing.JLabel();
        lblIdiomaS = new javax.swing.JLabel();
        lbl3DS = new javax.swing.JLabel();
        lblHorarioInicioS = new javax.swing.JLabel();
        lblHorarioFinS = new javax.swing.JLabel();
        lblFechaFuncion = new javax.swing.JLabel();
        lblSubtitulada = new javax.swing.JLabel();
        lblSubtituladaS = new javax.swing.JLabel();
        txtCantidadBoletos = new javax.swing.JTextField();
        lblCantidadBoletos = new javax.swing.JLabel();
        lblFechaS = new javax.swing.JLabel();
        lblPrecioEntradaIndividualS = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listAsientosS = new javax.swing.JList<>();
        btnConfirmacion = new javax.swing.JButton();
        lblAsientosSeleccionados = new javax.swing.JLabel();
        lblImporteT = new javax.swing.JLabel();
        lblImporteTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        lblCarteleraActual.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblCarteleraActual.setText("Cartelera actual: ");

        tblCartelera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCartelera);

        tblFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblFunciones);

        lblFuncionesxPelicula.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblFuncionesxPelicula.setText("Funciones disponibles para la pelicula seleccionada");

        lblPelicula.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblPelicula.setText("Pelicula");

        lblPrecioEntradaIndividual.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblPrecioEntradaIndividual.setText("Precio entrada individual");

        lblPeliculaS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N

        lblGeneros.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblGeneros.setText("Genero/s");

        lblGenerosS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N

        lblNumeroSala.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblNumeroSala.setText("Número de sala");

        lblidioma.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblidioma.setText("Idioma");

        lbl3D.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lbl3D.setText("3D");

        lblHorarioInicio.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblHorarioInicio.setText("Horario de inicio");

        lblHorarioFin.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblHorarioFin.setText("Horario de finalización");

        lblNumeroSalaS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N

        lblIdiomaS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N

        lbl3DS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N

        lblHorarioInicioS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N

        lblHorarioFinS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N

        lblFechaFuncion.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblFechaFuncion.setText("Fecha de la funcion");

        lblSubtitulada.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblSubtitulada.setText("Subtitulada");

        lblSubtituladaS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N

        lblCantidadBoletos.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblCantidadBoletos.setText("Cantidad de boletos");

        lblFechaS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N

        lblPrecioEntradaIndividualS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N

        jScrollPane3.setViewportView(listAsientosS);

        btnConfirmacion.setText("Confirmar cantidad de boletos");
        btnConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmacionActionPerformed(evt);
            }
        });

        lblAsientosSeleccionados.setText("Asientos seleccionados");

        lblImporteT.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblImporteT.setText("Importe total");

        jButton1.setText("Realizar compra");

        javax.swing.GroupLayout pnlTaquillaLayout = new javax.swing.GroupLayout(pnlTaquilla);
        pnlTaquilla.setLayout(pnlTaquillaLayout);
        pnlTaquillaLayout.setHorizontalGroup(
            pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaquillaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarteleraActual)
                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                        .addComponent(lblPelicula)
                        .addGap(65, 65, 65)
                        .addComponent(lblPeliculaS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblPrecioEntradaIndividual)
                        .addGap(30, 30, 30)
                        .addComponent(lblPrecioEntradaIndividualS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblAsientosSeleccionados))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFuncionesxPelicula)
                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGeneros)
                            .addComponent(lblNumeroSala)
                            .addComponent(lblidioma)
                            .addComponent(lbl3D)
                            .addComponent(lblSubtitulada))
                        .addGap(21, 21, 21)
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGenerosS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroSalaS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdiomaS, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl3DS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubtituladaS, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                        .addComponent(lblHorarioInicio)
                                        .addGap(78, 78, 78)
                                        .addComponent(lblHorarioInicioS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                        .addComponent(lblHorarioFin)
                                        .addGap(44, 44, 44)
                                        .addComponent(lblHorarioFinS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                        .addComponent(lblFechaFuncion)
                                        .addGap(61, 61, 61)
                                        .addComponent(lblFechaS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnConfirmacion)))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaquillaLayout.createSequentialGroup()
                                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                        .addComponent(lblImporteT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                                        .addComponent(lblCantidadBoletos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCantidadBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        pnlTaquillaLayout.setVerticalGroup(
            pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaquillaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCarteleraActual)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lblFuncionesxPelicula)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPelicula)
                    .addComponent(lblPeliculaS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioEntradaIndividual)
                    .addComponent(lblPrecioEntradaIndividualS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsientosSeleccionados))
                .addGap(10, 10, 10)
                .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                        .addComponent(lblGeneros)
                        .addGap(14, 14, 14)
                        .addComponent(lblNumeroSala)
                        .addGap(14, 14, 14)
                        .addComponent(lblidioma)
                        .addGap(14, 14, 14)
                        .addComponent(lbl3D)
                        .addGap(14, 14, 14)
                        .addComponent(lblSubtitulada))
                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                        .addComponent(lblGenerosS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblNumeroSalaS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblIdiomaS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbl3DS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblSubtituladaS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTaquillaLayout.createSequentialGroup()
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHorarioInicio)
                            .addComponent(lblHorarioInicioS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHorarioFin)
                            .addComponent(lblHorarioFinS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaFuncion)
                            .addComponent(lblFechaS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidadBoletos)
                            .addComponent(txtCantidadBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlTaquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImporteT)
                            .addComponent(lblImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(btnConfirmacion))
                    .addComponent(jButton1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTaquilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTaquilla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmacionActionPerformed
        try {
            int cantidad = Integer.parseInt(txtCantidadBoletos.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un numero valido.");
        }

    }//GEN-LAST:event_btnConfirmacionActionPerformed

    public void ocultarIDs() {

        TableColumnModel modeloColumnasP = tblCartelera.getColumnModel();
        TableColumnModel modeloColumnasF = tblFunciones.getColumnModel();
        TableColumn columnaP = modeloColumnasP.getColumn(0);
        TableColumn columnaF = modeloColumnasF.getColumn(0);
        columnaP.setMaxWidth(0);
        columnaP.setMinWidth(0);
        columnaP.setPreferredWidth(0);
        columnaP.setResizable(false);

        columnaF.setMaxWidth(0);
        columnaF.setMinWidth(0);
        columnaF.setPreferredWidth(0);
        columnaF.setResizable(false);
    }

    public void rellenarTablaPelicula() {
        DefaultTableModel modelo = (DefaultTableModel) tblCartelera.getModel();
        modelo.setRowCount(0);
        for (Pelicula p : listaCartelera) {
            modelo.addRow(new Object[]{p.getId_Pelicula(),
                p.getTitulo(),
                p.getDirector(),
                p.getReparto(),
                p.getPais_Origen(),
                p.getGenero()
            });
        }
    }

    public void rellenarTablaFunciones(int id_pelicula) {
        DefaultTableModel modelo = (DefaultTableModel) tblFunciones.getModel();
        modelo.setRowCount(0);
        listaFuncionPorPelicula = new ArrayList<>();
        try {
            listaFuncionPorPelicula = maniFuncion.listadoPorId(id_pelicula);
            String[] cabeceraFunciones = {"id_funcion", "Número de sala", "Idioma", "3D", "Hora de inicio", "Hora finalización", "Precio de entrada",
        "Fecha de función", "Subtitulada"};
            for (Funcion f : listaFuncionPorPelicula) {
                modelo.addRow(new Object[]{f.getId_Funcion(),
                    f.getNro_Sala(),
                    f.getIdioma(),
                    f.isEs3D(),
                    f.getHora_Inicio(),
                    f.getHora_Fin(),
                    f.getPrecio_Entrada(),
                    f.getFecha_Funcion(),
                    f.isSubtitulada()
                });
            }
        } catch(Exception e){
            e.printStackTrace();
        }

    }
    
    public void agregarListenerCartelera(){
        tblCartelera.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override 
            public void valueChanged(ListSelectionEvent evento){
                if(evento.getValueIsAdjusting()){
                    return;
                }
                int filaS = tblCartelera.getSelectedRow();
                if(filaS != -1){
                    id_peliculaS = (int)tblCartelera.getValueAt(filaS, 0);
                    rellenarTablaFunciones(id_peliculaS);
                    lblPeliculaS.setText((String) tblCartelera.getValueAt(filaS, 1));
                    lblGenerosS.setText((String) tblCartelera.getValueAt(filaS, 5));
                    
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl3D;
    private javax.swing.JLabel lbl3DS;
    private javax.swing.JLabel lblAsientosSeleccionados;
    private javax.swing.JLabel lblCantidadBoletos;
    private javax.swing.JLabel lblCarteleraActual;
    private javax.swing.JLabel lblFechaFuncion;
    private javax.swing.JLabel lblFechaS;
    private javax.swing.JLabel lblFuncionesxPelicula;
    private javax.swing.JLabel lblGeneros;
    private javax.swing.JLabel lblGenerosS;
    private javax.swing.JLabel lblHorarioFin;
    private javax.swing.JLabel lblHorarioFinS;
    private javax.swing.JLabel lblHorarioInicio;
    private javax.swing.JLabel lblHorarioInicioS;
    private javax.swing.JLabel lblIdiomaS;
    private javax.swing.JLabel lblImporteT;
    private javax.swing.JLabel lblImporteTotal;
    private javax.swing.JLabel lblNumeroSala;
    private javax.swing.JLabel lblNumeroSalaS;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblPeliculaS;
    private javax.swing.JLabel lblPrecioEntradaIndividual;
    private javax.swing.JLabel lblPrecioEntradaIndividualS;
    private javax.swing.JLabel lblSubtitulada;
    private javax.swing.JLabel lblSubtituladaS;
    private javax.swing.JLabel lblidioma;
    private javax.swing.JList<String> listAsientosS;
    private javax.swing.JPanel pnlTaquilla;
    private javax.swing.JTable tblCartelera;
    private javax.swing.JTable tblFunciones;
    private javax.swing.JTextField txtCantidadBoletos;
    // End of variables declaration//GEN-END:variables
}
