/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasAdministrativo;

import Controlador.ClienteDAO;
import Controlador.DetalleTicketDAO;
import Controlador.FuncionDAO;
import Controlador.PeliculaDAO;
import Controlador.VentaDAO;
import Modelo.Cliente;
import Modelo.DetalleTicket;
import Modelo.Funcion;
import Modelo.Pelicula;
import Modelo.Venta;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Enzo_2
 */
public class TicketsInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentasInternal
     */
    List<Pelicula> listaPeliculas;
    List<Funcion> listaFunciones;
    List<DetalleTicket> listaTickets;
    
    String[] cabeceraTickets = {"id_ticket", "DNI (Cliente)", "Medio de compra", "Fecha emisión", "Estado", "Sala", "Asiento"};
    String[] cabeceraFunciones = {"id_funcion", "Sala", "Pelicula", "Idioma", "Hora de inicio", "Hora finalización","3D", "Subtitulada" 
            ,"Precio de entrada", "Fecha de función", "Estado"};
    
    PeliculaDAO maniPeli = new PeliculaDAO();
    FuncionDAO maniFuncion = new FuncionDAO();
    DetalleTicketDAO maniTickets = new DetalleTicketDAO();
    ClienteDAO maniCliente = new ClienteDAO();
    VentaDAO maniVenta = new VentaDAO();
    
    int idFuncion = -1;

    public TicketsInternal() {
        initComponents();
        buttonGroup1.add(rbtnFiltroFecha);
        buttonGroup1.add(rbtnFiltroFechaPelicula);
        tblFunciones.setModel(VentanaAdministrativo.armarCabeceras(cabeceraFunciones));
        tblTickets.setModel(VentanaAdministrativo.armarCabeceras(cabeceraTickets));
        ocultarIDs();
        try {
            listaPeliculas = maniPeli.listarTodasPeliculas();
            listaFunciones = maniFuncion.listarFunciones();
            listaTickets = maniTickets.listarTickets();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void ocultarIDs() {

        TableColumnModel modeloColumnasP = tblFunciones.getColumnModel();
        TableColumnModel modeloColumnasF = tblTickets.getColumnModel();
        TableColumn columnaP = modeloColumnasP.getColumn(0);
        TableColumn columnaF = modeloColumnasF.getColumn(0);
        columnaP.setMaxWidth(0);
        columnaP.setMinWidth(0);
        columnaP.setPreferredWidth(0);
        columnaP.setResizable(false);

        columnaF.setMaxWidth(0);
        columnaF.setMinWidth(0);
        columnaF.setPreferredWidth(0);
        columnaF.setResizable(false);
    }
    
    public void rellenarTablaFunciones(){
        DefaultTableModel modelo = (DefaultTableModel) tblFunciones.getModel();
        modelo.setRowCount(0);
        
        
    }
    
    public void rellenarTablaTickets(){
        DefaultTableModel modelo = (DefaultTableModel) tblTickets.getModel();
        modelo.setRowCount(0);
        
        for(DetalleTicket dt : listaTickets){
            
            
            modelo.addRow(new Object[]{
                
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlVentas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTickets = new javax.swing.JTable();
        rbtnFiltroFecha = new javax.swing.JRadioButton();
        rbtnFiltroFechaPelicula = new javax.swing.JRadioButton();
        txtBuscarPelicula = new javax.swing.JTextField();
        txtFechaMin = new javax.swing.JTextField();
        lblNombrePelicula = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblEntre = new javax.swing.JLabel();
        txtFechaMax = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFunciones = new javax.swing.JTable();
        rbtnFiltroDNI = new javax.swing.JRadioButton();
        txtDNICliente = new javax.swing.JTextField();
        btnBaja = new javax.swing.JButton();
        lblGestionTickets = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        lblFuncion = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        lblIdioma = new javax.swing.JLabel();
        lblSala = new javax.swing.JLabel();
        lbl3D = new javax.swing.JLabel();
        lblHoraInicio = new javax.swing.JLabel();
        lblHoraFin = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblFechaFuncion = new javax.swing.JLabel();
        lblSubtitulada = new javax.swing.JLabel();
        checkFiltrarFuncion = new javax.swing.JCheckBox();

        tblTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTickets);

        rbtnFiltroFecha.setText("Filtrar por fecha");

        rbtnFiltroFechaPelicula.setText("Filtrar por fecha y pelicula");

        lblNombrePelicula.setText("Nombre de pelicula:");

        lblFecha.setText("Fecha:");

        lblEntre.setText("Entre");

        tblFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblFunciones);

        rbtnFiltroDNI.setText("Filtrar por DNI de cliente");

        btnBaja.setText("Dar de baja ticket");

        lblGestionTickets.setText("Gestión de tickets");

        btnModificar.setText("Modificar ticket");

        btnAlta.setText("Dar alta ticket");

        lblFuncion.setText("Función asignada al ticket:");

        lblPelicula.setText("Pelicula:");

        lblIdioma.setText("Idioma:");

        lblSala.setText("Sala:");

        lbl3D.setText("3D:");

        lblHoraInicio.setText("Hora inicio:");

        lblHoraFin.setText("Hora fin:");

        lblPrecio.setText("Precio:");

        lblFechaFuncion.setText("Fecha función:");

        lblSubtitulada.setText("Subtitulada:");

        checkFiltrarFuncion.setText("Filtrar por función");

        javax.swing.GroupLayout pnlVentasLayout = new javax.swing.GroupLayout(pnlVentas);
        pnlVentas.setLayout(pnlVentasLayout);
        pnlVentasLayout.setHorizontalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasLayout.createSequentialGroup()
                .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addComponent(lblFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(7, 7, 7))
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSala, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlVentasLayout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(lblPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl3D, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSubtitulada, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblGestionTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(lblFecha))
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(rbtnFiltroFecha)
                        .addGap(24, 24, 24)
                        .addComponent(rbtnFiltroFechaPelicula)
                        .addGap(32, 32, 32)
                        .addComponent(txtFechaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblEntre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtFechaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(rbtnFiltroDNI)
                        .addGap(13, 13, 13)
                        .addComponent(txtDNICliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(81, 81, 81)
                        .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addComponent(lblNombrePelicula)
                                .addGap(59, 59, 59)
                                .addComponent(checkFiltrarFuncion))))
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlVentasLayout.setVerticalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblGestionTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta)
                    .addComponent(btnBaja)
                    .addComponent(checkFiltrarFuncion)
                    .addComponent(lblNombrePelicula))
                .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar))
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtBuscarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lblFechaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lbl3D, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(lblSubtitulada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(lblHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFuncion)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblFecha))
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSala, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140)
                        .addComponent(lblHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnFiltroFecha)
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(rbtnFiltroFechaPelicula))
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtFechaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblEntre))
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(rbtnFiltroDNI))
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtDNICliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtFechaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkFiltrarFuncion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl3D;
    private javax.swing.JLabel lblEntre;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaFuncion;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JLabel lblGestionTickets;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblNombrePelicula;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSala;
    private javax.swing.JLabel lblSubtitulada;
    private javax.swing.JPanel pnlVentas;
    private javax.swing.JRadioButton rbtnFiltroDNI;
    private javax.swing.JRadioButton rbtnFiltroFecha;
    private javax.swing.JRadioButton rbtnFiltroFechaPelicula;
    private javax.swing.JTable tblFunciones;
    private javax.swing.JTable tblTickets;
    private javax.swing.JTextField txtBuscarPelicula;
    private javax.swing.JTextField txtDNICliente;
    private javax.swing.JTextField txtFechaMax;
    private javax.swing.JTextField txtFechaMin;
    // End of variables declaration//GEN-END:variables
}
