/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasCliente;

import Controlador.ClienteDAO;
import Controlador.DetalleTicketDAO;
import Controlador.FuncionDAO;
import Controlador.PeliculaDAO;
import Controlador.VentaDAO;
import Modelo.Asiento;
import Modelo.Cliente;
import Modelo.DetalleTicket;
import Modelo.Funcion;
import Modelo.Pelicula;
import Modelo.Venta;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Naiara
 */
public class DialogCompra extends javax.swing.JDialog {

    /**
     * Creates new form DialogCompra
     */
    List<Asiento> listaAsientos = null;
    VentaDAO maniVenta = new VentaDAO();
    FuncionDAO maniFuncion = new FuncionDAO();
    DetalleTicketDAO maniTicket = new DetalleTicketDAO();
    PeliculaDAO maniPeli = new PeliculaDAO();
    ClienteDAO maniCliente = new ClienteDAO();
    Venta venta = null;
    Funcion funcion = null;
    Pelicula peli = null;
    Cliente cliente = null;
    int dniCliente = 0;
    int token = 0;
    DefaultListModel<String> listModel;
    boolean estado = false;

    public DialogCompra(java.awt.Frame parent, boolean modal, List<Asiento> listaAsientos, Venta venta, String medio_pago, int id_funcion) throws Exception {
        super(parent, modal);
        initComponents();
        this.listaAsientos = listaAsientos;
        this.venta = venta;
        this.token = maniTicket.generarToken();
        this.funcion = maniFuncion.buscarFuncionPorId(id_funcion);
        this.peli = maniPeli.buscarPorId(funcion.getId_pelicula());
        rellenarTablaEntradas();
        setearDetalleVenta(venta);
        agregarListenerTabla();
        habilitarSegunMedioPago(medio_pago);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jbNroTarjeta = new javax.swing.JLabel();
        txtNroTarj = new javax.swing.JTextField();
        jbNomApeTarj = new javax.swing.JLabel();
        txtNomApeTarj = new javax.swing.JTextField();
        jbFechaVTarj = new javax.swing.JLabel();
        jbCVV = new javax.swing.JLabel();
        txtCVV = new javax.swing.JTextField();
        txtFechaVencimiento = new javax.swing.JTextField();
        pnlDetalleVenta = new javax.swing.JPanel();
        jbNomApeTarj1 = new javax.swing.JLabel();
        lblEntradasS = new javax.swing.JLabel();
        lblImporteTotalS = new javax.swing.JLabel();
        lblFechaVentaS = new javax.swing.JLabel();
        lblTokenS = new javax.swing.JLabel();
        lblCantEntradas = new javax.swing.JLabel();
        lblImporteTotal = new javax.swing.JLabel();
        lblFechaVenta = new javax.swing.JLabel();
        lblToken = new javax.swing.JLabel();
        lblMedioPagoS = new javax.swing.JLabel();
        lblMedioPago = new javax.swing.JLabel();
        pnlTicketIndividual = new javax.swing.JPanel();
        lblTicketS = new javax.swing.JLabel();
        lblPeliculaS = new javax.swing.JLabel();
        lblNumeroSalaS = new javax.swing.JLabel();
        lblAsientoS = new javax.swing.JLabel();
        lblFechaEmisionS = new javax.swing.JLabel();
        lblHorarioS = new javax.swing.JLabel();
        lblSubtituladaS = new javax.swing.JLabel();
        lbl3DS = new javax.swing.JLabel();
        lblFechaFuncionS = new javax.swing.JLabel();
        lblPrecioEntradaS = new javax.swing.JLabel();
        lblNumeroSala = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        lblFechaEmision = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblAsiento = new javax.swing.JLabel();
        lblSubtitulada = new javax.swing.JLabel();
        lbl3D = new javax.swing.JLabel();
        lblFechaFuncion = new javax.swing.JLabel();
        lblPrecioEntrada = new javax.swing.JLabel();
        pnlEfectivo = new javax.swing.JPanel();
        lblVuelto = new javax.swing.JLabel();
        txtEfectivo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnConfirmarCompra = new javax.swing.JButton();
        btnCancelarCompra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEntradas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(236, 252));

        jbNroTarjeta.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbNroTarjeta.setText("Nro. Tarjeta:");

        jbNomApeTarj.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbNomApeTarj.setText("Nombre y Apellido:");

        jbFechaVTarj.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbFechaVTarj.setText("Fecha vencimiento:");

        jbCVV.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbCVV.setText("CVV:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbNroTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbNomApeTarj, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbFechaVTarj, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(jbCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNroTarj, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(txtNomApeTarj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNroTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNroTarj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbNomApeTarj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomApeTarj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbFechaVTarj)
                    .addComponent(jbCVV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnlDetalleVenta.setPreferredSize(new java.awt.Dimension(236, 252));

        jbNomApeTarj1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbNomApeTarj1.setText("Detalle de venta");

        lblEntradasS.setText("Cantidad de entradas:");

        lblImporteTotalS.setText("Importe total:");

        lblFechaVentaS.setText("Fecha de la venta:");

        lblTokenS.setText("TOKEN PARA RETIRAR ONLINE:");

        lblMedioPagoS.setText("Medio de pago:");

        javax.swing.GroupLayout pnlDetalleVentaLayout = new javax.swing.GroupLayout(pnlDetalleVenta);
        pnlDetalleVenta.setLayout(pnlDetalleVentaLayout);
        pnlDetalleVentaLayout.setHorizontalGroup(
            pnlDetalleVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleVentaLayout.createSequentialGroup()
                .addGroup(pnlDetalleVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleVentaLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jbNomApeTarj1))
                    .addGroup(pnlDetalleVentaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pnlDetalleVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblImporteTotalS)
                            .addComponent(lblTokenS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaVentaS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEntradasS)
                            .addComponent(lblToken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblImporteTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCantEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMedioPagoS)
                            .addComponent(lblMedioPago, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlDetalleVentaLayout.setVerticalGroup(
            pnlDetalleVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNomApeTarj1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEntradasS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImporteTotalS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFechaVentaS)
                .addGap(18, 18, 18)
                .addComponent(lblFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMedioPagoS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTokenS)
                .addGap(18, 18, 18)
                .addComponent(lblToken, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lblTicketS.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lblTicketS.setText("Ticket");

        lblPeliculaS.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblPeliculaS.setText("Pelicula:");

        lblNumeroSalaS.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblNumeroSalaS.setText("Número de sala:");

        lblAsientoS.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblAsientoS.setText("Asiento asiento:");

        lblFechaEmisionS.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblFechaEmisionS.setText("Fecha emisión:");

        lblHorarioS.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblHorarioS.setText("Horario:");

        lblSubtituladaS.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblSubtituladaS.setText("Subtitulada:");

        lbl3DS.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lbl3DS.setText("3D:");

        lblFechaFuncionS.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblFechaFuncionS.setText("Fecha de función:");

        lblPrecioEntradaS.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblPrecioEntradaS.setText("Precio entrada:");

        lblNumeroSala.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        lblPelicula.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        lblFechaEmision.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        lblHorario.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        lblAsiento.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        lblSubtitulada.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        lbl3D.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        lblFechaFuncion.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        lblPrecioEntrada.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlTicketIndividualLayout = new javax.swing.GroupLayout(pnlTicketIndividual);
        pnlTicketIndividual.setLayout(pnlTicketIndividualLayout);
        pnlTicketIndividualLayout.setHorizontalGroup(
            pnlTicketIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTicketIndividualLayout.createSequentialGroup()
                .addGroup(pnlTicketIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTicketIndividualLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblTicketS, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTicketIndividualLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlTicketIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTicketIndividualLayout.createSequentialGroup()
                                .addComponent(lblPrecioEntradaS, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPrecioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTicketIndividualLayout.createSequentialGroup()
                                .addComponent(lblHorarioS, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTicketIndividualLayout.createSequentialGroup()
                                .addComponent(lblPeliculaS, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTicketIndividualLayout.createSequentialGroup()
                                .addComponent(lblFechaEmisionS, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTicketIndividualLayout.createSequentialGroup()
                                .addComponent(lblAsientoS, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTicketIndividualLayout.createSequentialGroup()
                                .addComponent(lblSubtituladaS, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblSubtitulada, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTicketIndividualLayout.createSequentialGroup()
                                .addComponent(lbl3DS, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl3D, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTicketIndividualLayout.createSequentialGroup()
                                .addComponent(lblFechaFuncionS, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblFechaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTicketIndividualLayout.createSequentialGroup()
                                .addComponent(lblNumeroSalaS, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNumeroSala, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlTicketIndividualLayout.setVerticalGroup(
            pnlTicketIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTicketIndividualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTicketS, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTicketIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeliculaS)
                    .addComponent(lblPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTicketIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroSalaS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroSala, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTicketIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsientoS)
                    .addComponent(lblAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTicketIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEmisionS)
                    .addComponent(lblFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTicketIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorarioS)
                    .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTicketIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtituladaS)
                    .addComponent(lblSubtitulada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTicketIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3DS)
                    .addComponent(lbl3D, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTicketIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaFuncionS)
                    .addComponent(lblFechaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTicketIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioEntradaS)
                    .addComponent(lblPrecioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtEfectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEfectivoKeyReleased(evt);
            }
        });

        jLabel1.setText("Vuelto correspondiente");

        jLabel3.setText("Con cuanto va a pagar:");

        javax.swing.GroupLayout pnlEfectivoLayout = new javax.swing.GroupLayout(pnlEfectivo);
        pnlEfectivo.setLayout(pnlEfectivoLayout);
        pnlEfectivoLayout.setHorizontalGroup(
            pnlEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEfectivoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(lblVuelto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlEfectivoLayout.setVerticalGroup(
            pnlEfectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEfectivoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        btnConfirmarCompra.setText("Confirmar compra");
        btnConfirmarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCompraActionPerformed(evt);
            }
        });

        btnCancelarCompra.setText("Cancelar");
        btnCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCompraActionPerformed(evt);
            }
        });

        tblEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblEntradas);

        jLabel2.setText("Entradas");

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(pnlDetalleVenta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(pnlTicketIndividual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(pnlEfectivo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnConfirmarCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCancelarCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(pnlDetalleVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(pnlTicketIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirmarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTicketIndividual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDetalleVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnConfirmarCompra)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarCompra)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEfectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEfectivoKeyReleased
        String efectivoString = txtEfectivo.getText();
        try {
            double pago = Double.parseDouble(efectivoString);
            if (pago < venta.getImporte_Total()) {
                lblVuelto.setText("0");
            } else {
                double vuelto = pago - venta.getImporte_Total();
                lblVuelto.setText(Double.toString(vuelto));
            }

        } catch (NumberFormatException a) {
            lblVuelto.setText("0");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_txtEfectivoKeyReleased

    private void btnConfirmarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCompraActionPerformed
        int seleccion = JOptionPane.showConfirmDialog(this, "¿El cliente quiere relacionar la compra con su cuenta? Si es asi ingrese su DNI", "Confirmación", YES_NO_OPTION);
        if (seleccion == 0) {
            String dni = JOptionPane.showInputDialog("Ingrese DNI");
            try {
                if (dni.isEmpty() || dni.length() < 8) {
                    JOptionPane.showMessageDialog(this, "No puede dejar el campo vacio y debe ingresar un DNI de 8 caracteres.");
                    return;
                }

                int dniNumero = Integer.parseInt(dni);
                dniCliente = dniNumero;
                cliente = maniCliente.buscarClientePorDNI(dniCliente);

                if (cliente == null) {
                    JOptionPane.showMessageDialog(this, "No se ha encontrado el cliente con el DNI asignado.");
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese un DNI valido.");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        /*
        String nroTarjeta = txtNroTarj.getText();
        String nombreCompleto = txtNomApeTarj.getText();
        String codigoSeguridad = txtCVV.getText();
        try {
            if(nroTarjeta.isEmpty() || nombreCompleto.isEmpty() || codigoSeguridad.isEmpty()){
                JOptionPane.showMessageDialog(this, "No puede dejar campos vacios en los datos de tarjeta");
                return;
            } else {
                if((nroTarjeta.length() < 13 || nroTarjeta.length() > 19) || (nombreCompleto.length() < 3 || nombreCompleto.length() > 50) || codigoSeguridad.length() < 3){
                    JOptionPane.showMessageDialog(this, "Ingrese campos correctos para los datos de tarjeta.");
                    return;
                }
            }
            
            for(char caracter : nombreCompleto.toCharArray()){
                if(Character.isDigit(caracter)){
                    JOptionPane.showMessageDialog(this, "El nombre no puede tener caracteres numericos");
                    return;
                }
            }
           
            
            Integer nro = Integer.parseInt(nroTarjeta);
            int codigo = Integer.parseInt(codigoSeguridad);
            
            
            int idVenta = maniVenta.registrarVentaTaquilla(venta);
            for (Asiento asiento : listaAsientos) {
                DetalleTicket ticket = new DetalleTicket(funcion.getId_Funcion(), asiento.getId_asiento(), idVenta, LocalDate.now(), true);
                maniTicket.generarTicket(ticket);
                estado = true;
            }
            JOptionPane.showMessageDialog(this, "Venta y tickets generados correctamente.");
         */

        //Hay que eliminar esto despues asi noo se hace lioso probar  y descomentar lo anterior
        try {
            if (cliente != null) {
                venta.setId_Cliente(cliente.getId_cliente());
            }
            venta.setId_Cliente(cliente.getId_cliente());
            int idVenta = maniVenta.registrarVentaTaquilla(venta);
            for (Asiento asiento : listaAsientos) {
                DetalleTicket ticket = new DetalleTicket(funcion.getId_Funcion(), asiento.getId_asiento(), idVenta, LocalDate.now(), true);
                maniTicket.generarTicket(ticket);
                estado = true;
            }
            JOptionPane.showMessageDialog(this, "Venta y tickets generados correctamente.");
            // aca termina
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error en los datos de tarjetas.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnConfirmarCompraActionPerformed

    private void btnCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCompraActionPerformed
        estado = false;
        this.dispose();
    }//GEN-LAST:event_btnCancelarCompraActionPerformed

    public boolean isEstado() {
        return estado;
    }

    public void setearDetalleVenta(Venta venta) {
        lblImporteTotal.setText(Double.toString(venta.getImporte_Total()));
        lblCantEntradas.setText(Integer.toString(venta.getCantidad_Entradas()));
        lblFechaVenta.setText(venta.getFecha_Venta().toString());
        lblMedioPago.setText((String) venta.getMedio_Pago());
        if (venta.getMedio_Compra().equalsIgnoreCase("online")) {
            lblToken.setText(Integer.toString(token));
        } else {
            lblToken.setText("---------------");
        }
    }

    public void rellenarTablaEntradas() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modelo.addColumn("Fila asiento");
        modelo.addColumn("Numero asiento");
        for (Asiento a : listaAsientos) {
            modelo.addRow(new Object[]{
                a.getFila_asiento(),
                a.getNumero_asiento()
            });
        }
        tblEntradas.setModel(modelo);
    }

    public void agregarListenerTabla() {
        tblEntradas.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent evento) {
                if (evento.getValueIsAdjusting()) {
                    return;
                }

                int filaS = tblEntradas.getSelectedRow();
                if (filaS != -1) {
                    lblAsiento.setText(tblEntradas.getValueAt(filaS, 0) + " - " + tblEntradas.getValueAt(filaS, 1));
                    lblPelicula.setText(peli.getTitulo());
                    lblNumeroSala.setText(Integer.toString(funcion.getNro_Sala()));
                    lblSubtitulada.setText(parsearBoolean(funcion.isSubtitulada()));
                    lbl3D.setText(parsearBoolean(funcion.isEs3D()));
                    lblFechaFuncion.setText(funcion.getFecha_Funcion().toString());
                    lblPrecioEntrada.setText(Double.toString(funcion.getPrecio_Entrada()));
                    lblHorario.setText(funcion.getHora_Inicio().toString().substring(0, 5) + " - " + funcion.getHora_Fin().toString().substring(0, 5));

                }
            }
        });
    }

    public void habilitarSegunMedioPago(String medio_pago) {
        if (medio_pago.equalsIgnoreCase("debito")) {
            txtEfectivo.setEnabled(false);
        } else if (medio_pago.equalsIgnoreCase("efectivo")) {
            txtNroTarj.setEnabled(false);
            txtNomApeTarj.setEnabled(false);
            txtCVV.setEnabled(false);
            txtFechaVencimiento.setEnabled(false);
        }
    }

    public String parsearBoolean(boolean estado) {
        if (estado) {
            return "Si";
        }
        return "No";
    }

    public boolean parsearString(String estado) {
        return estado.equalsIgnoreCase("Si");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                List<Asiento> listaAsientos = null;
                Venta venta = null;
                String a = "";
                int id = 0;
                DialogCompra dialog = null;
                try {
                    dialog = new DialogCompra(new javax.swing.JFrame(), true, listaAsientos, venta, a, id);
                } catch (Exception ex) {
                    Logger.getLogger(DialogCompra.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCompra;
    private javax.swing.JButton btnConfirmarCompra;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jbCVV;
    private javax.swing.JLabel jbFechaVTarj;
    private javax.swing.JLabel jbNomApeTarj;
    private javax.swing.JLabel jbNomApeTarj1;
    private javax.swing.JLabel jbNroTarjeta;
    private javax.swing.JLabel lbl3D;
    private javax.swing.JLabel lbl3DS;
    private javax.swing.JLabel lblAsiento;
    private javax.swing.JLabel lblAsientoS;
    private javax.swing.JLabel lblCantEntradas;
    private javax.swing.JLabel lblEntradasS;
    private javax.swing.JLabel lblFechaEmision;
    private javax.swing.JLabel lblFechaEmisionS;
    private javax.swing.JLabel lblFechaFuncion;
    private javax.swing.JLabel lblFechaFuncionS;
    private javax.swing.JLabel lblFechaVenta;
    private javax.swing.JLabel lblFechaVentaS;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblHorarioS;
    private javax.swing.JLabel lblImporteTotal;
    private javax.swing.JLabel lblImporteTotalS;
    private javax.swing.JLabel lblMedioPago;
    private javax.swing.JLabel lblMedioPagoS;
    private javax.swing.JLabel lblNumeroSala;
    private javax.swing.JLabel lblNumeroSalaS;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblPeliculaS;
    private javax.swing.JLabel lblPrecioEntrada;
    private javax.swing.JLabel lblPrecioEntradaS;
    private javax.swing.JLabel lblSubtitulada;
    private javax.swing.JLabel lblSubtituladaS;
    private javax.swing.JLabel lblTicketS;
    private javax.swing.JLabel lblToken;
    private javax.swing.JLabel lblTokenS;
    private javax.swing.JLabel lblVuelto;
    private javax.swing.JPanel pnlDetalleVenta;
    private javax.swing.JPanel pnlEfectivo;
    private javax.swing.JPanel pnlTicketIndividual;
    private javax.swing.JTable tblEntradas;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JTextField txtFechaVencimiento;
    private javax.swing.JTextField txtNomApeTarj;
    private javax.swing.JTextField txtNroTarj;
    // End of variables declaration//GEN-END:variables
}
