/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasCliente;

import Controlador.AsientoDAO;
import Modelo.Asiento;
import java.util.List;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enzo_2
 */
public class DialogAsientos extends javax.swing.JDialog {

    /**
     * Creates new form DialogAsientos
     */
     
    AsientoDAO maniAsi = new AsientoDAO();
    List<Asiento> listaAsientos = maniAsi.listarAsientosPorSala(1);
    int nro_sala = 0;
    char fila = '\u0000';
    int numero = 0;
    public DialogAsientos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rellenarTabla();
        tblAsientos.setCellSelectionEnabled(true);
        tblAsientos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        agregarListener(tblAsientos);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        pnlAsientos = new javax.swing.JPanel();
        lblCinema = new javax.swing.JLabel();
        lblSala = new javax.swing.JLabel();
        lblNroSala = new javax.swing.JLabel();
        lblNombrePelicula = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        lblHorarioInicio = new javax.swing.JLabel();
        lblEmpieza = new javax.swing.JLabel();
        lblAsientos = new javax.swing.JLabel();
        lblAsientosLibres = new javax.swing.JLabel();
        lblFinaliza = new javax.swing.JLabel();
        lblHorarioFin = new javax.swing.JLabel();
        lblTipoPelicula = new javax.swing.JLabel();
        lblEsTipo = new javax.swing.JLabel();
        lblIdioma = new javax.swing.JLabel();
        lblIdiomaPelicula = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblGeneroPelicula = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        lblEstadoSub = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsientos = new javax.swing.JTable();
        pnlPantalla = new javax.swing.JPanel();
        lblPantalla = new javax.swing.JLabel();
        pnlEntrada = new javax.swing.JPanel();
        lblEntrada = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFilaS = new javax.swing.JLabel();
        lblNumeroS = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlAsientos.setBackground(new java.awt.Color(102, 0, 0));
        pnlAsientos.setForeground(new java.awt.Color(102, 0, 0));

        lblCinema.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblCinema.setForeground(new java.awt.Color(255, 255, 255));
        lblCinema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCinema.setText("CinemaCentro");
        lblCinema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSala.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblSala.setForeground(new java.awt.Color(255, 255, 255));
        lblSala.setText("SALA N°:");

        lblNroSala.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblNroSala.setForeground(new java.awt.Color(255, 255, 255));
        lblNroSala.setText("NUMEROSALA");

        lblNombrePelicula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblNombrePelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePelicula.setText("NOMBREPELICULA");

        lblPelicula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblPelicula.setText("PELICULA:");

        lblHorarioInicio.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblHorarioInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblHorarioInicio.setText("HORARIOINICIO");

        lblEmpieza.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblEmpieza.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpieza.setText("EMPIEZA:");

        lblAsientos.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblAsientos.setForeground(new java.awt.Color(255, 255, 255));
        lblAsientos.setText("ASIENTOS:");

        lblAsientosLibres.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblAsientosLibres.setForeground(new java.awt.Color(255, 255, 255));
        lblAsientosLibres.setText("ASIENTOSLIBRES");

        lblFinaliza.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblFinaliza.setForeground(new java.awt.Color(255, 255, 255));
        lblFinaliza.setText("FINALIZA:");

        lblHorarioFin.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblHorarioFin.setForeground(new java.awt.Color(255, 255, 255));
        lblHorarioFin.setText("HORARIOFINAL");

        lblTipoPelicula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblTipoPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoPelicula.setText("ES 2D/3D:");

        lblEsTipo.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblEsTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblEsTipo.setText("ES2D/3D");

        lblIdioma.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblIdioma.setForeground(new java.awt.Color(255, 255, 255));
        lblIdioma.setText("IDIOMA:");

        lblIdiomaPelicula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblIdiomaPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblIdiomaPelicula.setText("IDIOMAPELICULA");

        lblGenero.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setText("GENERO:");

        lblGeneroPelicula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblGeneroPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblGeneroPelicula.setText("GENEROPELICULA");

        lblSub.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblSub.setForeground(new java.awt.Color(255, 255, 255));
        lblSub.setText("SUBTITULADA:");

        lblEstadoSub.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblEstadoSub.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoSub.setText("SI/NO");

        tblAsientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "A", "B", "C", "D", "E", "F", "G", "H", "I", "J"
            }
        ));
        tblAsientos.setCellSelectionEnabled(true);
        tblAsientos.setRowHeight(23);
        jScrollPane1.setViewportView(tblAsientos);

        pnlPantalla.setBackground(new java.awt.Color(102, 0, 0));
        pnlPantalla.setForeground(new java.awt.Color(255, 255, 255));

        lblPantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pantalla.png"))); // NOI18N
        lblPantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlPantallaLayout = new javax.swing.GroupLayout(pnlPantalla);
        pnlPantalla.setLayout(pnlPantallaLayout);
        pnlPantallaLayout.setHorizontalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPantalla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPantallaLayout.setVerticalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addComponent(lblPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlEntrada.setBackground(new java.awt.Color(102, 0, 0));

        lblEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/entrada.png"))); // NOI18N
        lblEntrada.setMaximumSize(new java.awt.Dimension(200, 50));
        lblEntrada.setMinimumSize(new java.awt.Dimension(200, 50));
        lblEntrada.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout pnlEntradaLayout = new javax.swing.GroupLayout(pnlEntrada);
        pnlEntrada.setLayout(pnlEntradaLayout);
        pnlEntradaLayout.setHorizontalGroup(
            pnlEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEntradaLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(lblEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        pnlEntradaLayout.setVerticalGroup(
            pnlEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEntradaLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(lblEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fila seleccionada:");

        lblFilaS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblFilaS.setForeground(new java.awt.Color(255, 255, 255));

        lblNumeroS.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblNumeroS.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Numero de asiento seleccionado:");

        javax.swing.GroupLayout pnlAsientosLayout = new javax.swing.GroupLayout(pnlAsientos);
        pnlAsientos.setLayout(pnlAsientosLayout);
        pnlAsientosLayout.setHorizontalGroup(
            pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsientosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSala)
                    .addComponent(lblEmpieza)
                    .addComponent(lblGenero))
                .addGap(7, 7, 7)
                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addComponent(lblNroSala)
                        .addGap(19, 19, 19)
                        .addComponent(lblPelicula))
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblHorarioInicio)
                        .addGap(14, 14, 14)
                        .addComponent(lblFinaliza))
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addComponent(lblGeneroPelicula)
                        .addGap(13, 13, 13)
                        .addComponent(lblIdioma)))
                .addGap(6, 6, 6)
                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombrePelicula)
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblHorarioFin))
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblIdiomaPelicula)))
                .addGap(25, 25, 25)
                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoPelicula)
                    .addComponent(lblAsientos))
                .addGap(5, 5, 5)
                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addComponent(lblEsTipo)
                        .addGap(11, 11, 11)
                        .addComponent(lblSub))
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblAsientosLibres)))
                .addGap(18, 18, 18)
                .addComponent(lblEstadoSub)
                .addGap(11, 11, 11)
                .addComponent(lblCinema))
            .addGroup(pnlAsientosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(pnlEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlAsientosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pnlPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlAsientosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(lblFilaS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(lblNumeroS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(490, 490, 490)
                .addComponent(btnSalir))
        );
        pnlAsientosLayout.setVerticalGroup(
            pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsientosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addComponent(lblSala)
                        .addGap(4, 4, 4)
                        .addComponent(lblEmpieza)
                        .addGap(4, 4, 4)
                        .addComponent(lblGenero))
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNroSala)
                            .addComponent(lblPelicula))
                        .addGap(4, 4, 4)
                        .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHorarioInicio)
                            .addComponent(lblFinaliza))
                        .addGap(4, 4, 4)
                        .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGeneroPelicula)
                            .addComponent(lblIdioma)))
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addComponent(lblNombrePelicula)
                        .addGap(4, 4, 4)
                        .addComponent(lblHorarioFin)
                        .addGap(4, 4, 4)
                        .addComponent(lblIdiomaPelicula))
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addComponent(lblTipoPelicula)
                        .addGap(4, 4, 4)
                        .addComponent(lblAsientos))
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEsTipo)
                            .addComponent(lblSub))
                        .addGap(4, 4, 4)
                        .addComponent(lblAsientosLibres))
                    .addComponent(lblEstadoSub)
                    .addComponent(lblCinema, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(pnlEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAsientosLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(pnlPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblFilaS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lblNumeroS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    
    public void rellenarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tblAsientos.getModel();
        
        int columnas = modelo.getColumnCount();
        char fila = '\u0000';
        for(int i = 0; i < columnas; i++){
            fila = modelo.getColumnName(i).charAt(0);
            int contador = 0;
            for(Asiento a : listaAsientos){
                if(a.getFila_asiento() == fila){
                    modelo.setValueAt(a.getNumero_asiento() + " " + parsearBoolean(a.isEstado()), contador, i);
                    contador++;
                }
            }
        }
    }
    
    public String parsearBoolean(boolean estado){
        if(estado){
            return "Libre";
        } 
            return "Ocupado";
    } 
    
    public boolean parsearString(String estado){
        return estado.equalsIgnoreCase("Libre");
    }
    
    public void agregarListener(JTable tabla){
        tabla.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent evento){
                if(evento.getValueIsAdjusting()){
                return;
                }

                int columnaS = tabla.getSelectedColumn();
                int filaS = tabla.getSelectedRow();
                String comprobacion = (String) tabla.getValueAt(filaS, columnaS);
                if(comprobacion == null){
                    return;
                }
                
                if(columnaS != -1 && filaS != -1){
                    String valores = (String) tabla.getValueAt(filaS, columnaS);
                    fila = ((String) tabla.getColumnName(columnaS)).charAt(0);
                    String[] valoresCortados = valores.split(" ");
                    numero = Integer.parseInt(valoresCortados[0]);
                    lblFilaS.setText(String.valueOf(fila));
                    lblNumeroS.setText(Integer.toString(numero));
                } 
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogAsientos dialog = new DialogAsientos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsientos;
    private javax.swing.JLabel lblAsientosLibres;
    private javax.swing.JLabel lblCinema;
    private javax.swing.JLabel lblEmpieza;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblEsTipo;
    private javax.swing.JLabel lblEstadoSub;
    private javax.swing.JLabel lblFilaS;
    private javax.swing.JLabel lblFinaliza;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblGeneroPelicula;
    private javax.swing.JLabel lblHorarioFin;
    private javax.swing.JLabel lblHorarioInicio;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblIdiomaPelicula;
    private javax.swing.JLabel lblNombrePelicula;
    private javax.swing.JLabel lblNroSala;
    private javax.swing.JLabel lblNumeroS;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblSala;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblTipoPelicula;
    private javax.swing.JPanel pnlAsientos;
    private javax.swing.JPanel pnlEntrada;
    private javax.swing.JPanel pnlPantalla;
    private javax.swing.JTable tblAsientos;
    // End of variables declaration//GEN-END:variables
}
