/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasCliente;

import Controlador.FuncionDAO;
import Controlador.PeliculaDAO;
import Modelo.Cliente;
import Modelo.Funcion;
import Modelo.Pelicula;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Enzo_2
 */
public class VentanaMainCliente extends javax.swing.JFrame {

    int idFun = 0;
    private FuncionDAO maniFun = new FuncionDAO();
    static String[] columnasFun = {"id_funcion", "Día", "Horario Inicio/Fin", "Sala", "3D", "Idioma"};
    static DefaultTableModel modeloFun = new DefaultTableModel(null, columnasFun) {
        @Override
        public boolean isCellEditable(int a, int b) {
            return false;
        }
    };

    int idPeli = 0;
    private PeliculaDAO maniPeli = new PeliculaDAO();
    static String[] columnas = {"id_pelicula", "Título", "Género"};
    static DefaultTableModel modeloPeli = new DefaultTableModel(null, columnas) {
        @Override
        public boolean isCellEditable(int a, int b) {
            return false;
        }
    };

    public VentanaMainCliente(Cliente cliente) {
        initComponents();
        armarCabeceraPelicula(jTPeli);
    }

    private void tablaPeli() {

        List<Pelicula> lista;
        modeloPeli.setRowCount(0);
        try {
            lista = maniPeli.listarTodasPeliculas();
            for (Pelicula peli : lista) {
                modeloPeli.addRow(new Object[]{
                    peli.getId_Pelicula(),
                    peli.getTitulo(),
                    peli.getGenero()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void tablaFun() {

        ArrayList<Funcion> listaFun;
        modeloFun.setRowCount(0);
        try {
            listaFun = maniFun.listadoPorId(idPeli);
            for (Funcion fun : listaFun) {
                modeloFun.addRow(new Object[]{
                    fun.getId_Funcion(),
                    fun.getFecha_Funcion(),
                    "Inicio: " + fun.getHora_Inicio() + "\nFin: " + fun.getHora_Fin(),
                    fun.getNro_Sala(),
                    fun.isEs3D(),
                    fun.getIdioma()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    //Cabecera y relleno de tablas (pelicula y funcion)
    private void armarCabeceraPelicula(JTable tabla) {

        //Cabecera
        tabla.setModel(modeloPeli);
        TableColumnModel modeloColumnas = tabla.getColumnModel();
        TableColumn columnID = modeloColumnas.getColumn(0);
        columnID.setMinWidth(0);
        columnID.setPreferredWidth(0);
        columnID.setMaxWidth(0);
        columnID.setResizable(false);

        //relleno
        tablaPeli();
    }

    private void armarCabeceraFuncion(JTable tabla) {
        tabla.setModel(modeloFun);
        TableColumnModel modeloColumnas = tabla.getColumnModel();
        TableColumn columnID = modeloColumnas.getColumn(0);
        columnID.setMinWidth(0);
        columnID.setPreferredWidth(0);
        columnID.setMaxWidth(0);
        columnID.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbPelicula = new javax.swing.JLabel();
        jbFuncion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFuncion = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTPeli = new javax.swing.JTable();
        lblButaca = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jbCantidad = new javax.swing.JLabel();
        jBButaca = new javax.swing.JButton();
        jBComprar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jLabel1.setText("Taquilla Online");

        jbPelicula.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jbPelicula.setText("Pelicula");

        jbFuncion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jbFuncion.setText("Función:");

        jTFuncion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTFuncion);

        jTPeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTPeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPeliMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTPeli);

        lblButaca.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        lblButaca.setText("Butaca");

        jbCantidad.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jbCantidad.setText("Cantidad");

        jBButaca.setText("Seleccionar");
        jBButaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBButacaActionPerformed(evt);
            }
        });

        jBComprar.setText("Comprar");

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLoginLayout.createSequentialGroup()
                            .addGap(304, 304, 304)
                            .addComponent(jLabel1))
                        .addGroup(pnlLoginLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbPelicula)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbFuncion))))
                    .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLoginLayout.createSequentialGroup()
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(102, 102, 102)
                            .addComponent(jBButaca))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCantidad)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(lblButaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(jBComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jbPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jbFuncion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jBComprar)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jbCantidad)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbSalir)
                            .addComponent(lblButaca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBButaca)))
                .addGap(54, 107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBButacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBButacaActionPerformed
        JFrame padre = (JFrame) SwingUtilities.getWindowAncestor(this);
        DialogAsientos ventanaAsientos = new DialogAsientos(padre, true);
        ventanaAsientos.setVisible(true);
    }//GEN-LAST:event_jBButacaActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jTPeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPeliMouseClicked
        
        int filaSelec = jTPeli.getSelectedRow();
        if(filaSelec > -1){
            
            idPeli = (int) jTPeli.getValueAt(filaSelec, 0);
            
            tablaFun();
            
        }
        
    }//GEN-LAST:event_jTPeliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMainCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMainCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMainCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMainCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente cliente = null;
                new VentanaMainCliente(cliente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBButaca;
    private javax.swing.JButton jBComprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTFuncion;
    private javax.swing.JTable jTPeli;
    private javax.swing.JLabel jbCantidad;
    private javax.swing.JLabel jbFuncion;
    private javax.swing.JLabel jbPelicula;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel lblButaca;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
